--需插入账户数据
SELECT *
  FROM PB_ACC_INF ACC
 WHERE (AIF_CSTNO,AIF_ACCNO) NOT IN (select AIF_CSTNO, AIF_ACCNO from PB_ACC_INF_1212);

--需插入签约数据
SELECT *
  FROM PB_CERT_INF CERT
 WHERE (PCI_CSTNO, PCI_MEDIUMTYPE) NOT IN (select PCI_CSTNO, PCI_MEDIUMTYPE from PB_CERT_INF_1212);


--需更新客户信息 导出!!!!!!!!!
DROP TABLE TEM_MOVE_PB_CST_INF;
CREATE TABLE TEM_MOVE_PB_CST_INF AS
select CST.CIP_CSTNO, CST.CIP_CHARID
  from PB_CST_INF CST
 WHERE CIP_CSTNO IN (SELECT CIP_CSTNO
                       FROM (select *
                               from PB_CST_INF_1212
                             minus
                             select * from PB_CST_INF));

--需插入客户信息
SELECT *
  FROM PB_CST_INF cst
 WHERE (CIP_CSTNO) NOT IN (select CIP_CSTNO from PB_CST_INF_1212);


--常用联系人需插入
SELECT *
  FROM PB_REL_CST_BOOK book
 WHERE (PBK_ACCNO, PBK_MEMBERID, PBK_CHANNEL) NOT IN (select PBK_ACCNO, PBK_MEMBERID, PBK_CHANNEL from PB_REL_CST_BOOK_1212);


----需插入单笔 日累计限额数据
SELECT *
  FROM PB_CST_CURR_LIMIT lmt
 WHERE CCL_CSTNO NOT IN (select CCL_CSTNO from PB_CST_CURR_LIMIT_1212);


----需插入日笔数年限额限额数据
SELECT *
  FROM PB_CST_TRANS_LIMIT lmt
 WHERE CCL_CSTNO NOT IN (select CCL_CSTNO from PB_CST_TRANS_LIMIT_1212);



SELECT * FROM PB_CST_APP;
SELECT * FROM PB_CST_ITEM;
SELECT * FROM PB_ELECTRONIC_BILL;
SELECT * FROM PB_FIX_CURRENT_TRAN;
SELECT * FROM PB_TRANSFER;
SELECT * FROM PB_TRAN_FLOW;
SELECT * FROM CB_ACC_INF;
SELECT * FROM CB_AUTH_HISTORY;
SELECT * FROM CB_AUTH_DEF;
SELECT * FROM CB_AUTH_AREA;
SELECT * FROM CB_CST_BSN;
SELECT * FROM CB_AUTH_REF;
SELECT * FROM CB_CERT_INF;
SELECT * FROM CB_CST_INF;
SELECT * FROM CB_CST_NODE;
SELECT * FROM CB_CST_PAYEE;
SELECT * FROM CB_LIMIT_ACC;
SELECT * FROM CB_PRE_TRANFLOW;
SELECT * FROM CB_USER_ACC;
SELECT * FROM CB_USER_BSN;
SELECT * FROM CB_USER_INF;
SELECT * FROM CB_WAGE_DETAIL;
SELECT * FROM CB_TRANFLOW;
SELECT * FROM CB_FIN_FIXED;
SELECT * FROM CB_INFORM_DEPOSIT_OPEN;
SELECT * FROM CB_INFORM_WITHDRAW;
SELECT * FROM CB_WAGE_FLOW;
SELECT * FROM IM_OPERATION_FLOW;  需替换字段, 最后加commit;
SELECT * FROM PB_CST_INF_HIS;