SELECT DISTINCT CST.CIP_MOBILE AS 手机号,
                CST.CIP_NAME AS 客户姓名,
                TO_DATE(CST.CIP_EBANKTIME, 'yyyy-MM-dd hh24:mi:ss') AS 注册时间
  FROM T_CUSTOMER_0824 C, PB_CST_INF CST
 WHERE C.KERNEL_ID = CST.CIP_CIFNO
   AND STATUS != 0
   AND STATUS IS NOT NULL;
