DROP TABLE EB_ACCT_LIMIT;
CREATE TABLE EB_ACCT_LIMIT (BASE_ACCT_NO VARCHAR2(50 CHAR) NOT NULL, 
CLIENT_NO VARCHAR2(20 CHAR), 
EVERY_LIMIT NUMBER DEFAULT 0, 
DAY_LIMIT NUMBER DEFAULT 0, 
MONTH_LIMIT NUMBER DEFAULT 0, 
EXT1 VARCHAR2(50 CHAR), 
EXT2 VARCHAR2(50 CHAR), 
EXT3 VARCHAR2(50 CHAR));
