DROP TABLE EB_OPEN_INFO;
CREATE TABLE EB_OPEN_INFO
(
  BASE_ACCT_NO       VARCHAR2(50 CHAR)          NOT NULL,
  OPEN_DATE          VARCHAR2(10 CHAR),
  NEXT_YEARFEE_DATE  VARCHAR2(10 CHAR),
  MATURE_DATE        VARCHAR2(10 CHAR),
  OPEN_BRANCH        VARCHAR2(20 CHAR),
  TELLER_ID          VARCHAR2(20 CHAR),
  SALER_NAME         VARCHAR2(50 CHAR),
  EXT_1              VARCHAR2(50 CHAR),
  EXT_2              VARCHAR2(50 CHAR),
  EXT_3              VARCHAR2(50 CHAR),
  CARD_NO            VARCHAR2(50 CHAR),
  INDIVDUAL_FLAG     VARCHAR2(3 CHAR),
  EB_STATUS          VARCHAR2(3 CHAR)
);
