drop table RB_INT_DETAIL;
CREATE TABLE RB_INT_DETAIL
(
  INTERNAL_KEY                 NUMBER(12) CONSTRAINT RID_NN1 NOT NULL,
  CR_INT_TYPE                  VARCHAR2(3 CHAR),
  CR_PERIOD_FREQ               VARCHAR2(2 CHAR),
  CR_NEXT_CYCLE_DATE           DATE,
  CR_INT_DAY                   NUMBER(2),
  CR_ACCT_LEVEL_INT_RATE       NUMBER(13,8),
  CR_SPREAD_RATE               NUMBER(13,8),
  CR_INT_CAP                   VARCHAR2(1 CHAR) DEFAULT 'Y',
  CR_INT_ACCRUED               NUMBER           DEFAULT 0,
  CR_INT_ACCRUED_MTD           NUMBER           DEFAULT 0,
  CR_INT_ACCRUED_CTD           NUMBER           DEFAULT 0,
  CR_INT_ACCRUED_YTD           NUMBER           DEFAULT 0,
  CR_INT_ACCRUED_CALC_CTD      NUMBER           DEFAULT 0,
  CR_INT_PAID_MTD              NUMBER           DEFAULT 0,
  CR_INT_PAID_CTD              NUMBER           DEFAULT 0,
  CR_INT_PAID_YTD              NUMBER           DEFAULT 0,
  CR_INT_PAID_LAST_YEAR        NUMBER           DEFAULT 0,
  CR_INT_UNPOSTED_CTD          NUMBER           DEFAULT 0,
  CR_INT_POSTED                NUMBER           DEFAULT 0,
  CR_INT_UNPOSTED              NUMBER           DEFAULT 0,
  CR_INT_ADJ                   NUMBER           DEFAULT 0,
  CR_INT_ADJ_MTD               NUMBER           DEFAULT 0,
  CR_INT_ADJ_CTD               NUMBER           DEFAULT 0,
  CR_INT_ADJ_YTD               NUMBER           DEFAULT 0,
  CR_INT_ADJ_CALC_CTD          NUMBER           DEFAULT 0,
  CR_INT_ADJ_POSTED            NUMBER           DEFAULT 0,
  CR_INT_ADJ_PAID_MTD          NUMBER           DEFAULT 0,
  CR_INT_ADJ_PAID_CTD          NUMBER           DEFAULT 0,
  CR_INT_ADJ_PAID_YTD          NUMBER           DEFAULT 0,
  CR_INT_NOT_COLL_MTD          NUMBER           DEFAULT 0,
  CR_INT_ADJ_UNPOSTED_CTD      NUMBER           DEFAULT 0,
  CR_FREQUENCY_PERIOD          NUMBER(3),
  CR_FREQUENCY_TYPE            VARCHAR2(1 CHAR),
  CR_TD_PAYOUT                 VARCHAR2(1 CHAR) DEFAULT 'N',
  CR_TD_INT_PAYOUT             NUMBER           DEFAULT 0,
  CR_THIRD_PARTY_ACCT          NUMBER(12),
  CR_INT_CTRL_DATE             DATE,
  CR_LAST_CYCLE_DATE           DATE,
  CR_TAX_TYPE                  VARCHAR2(3 CHAR),
  CR_LAST_BACKDATE_ACCR        DATE,
  DR_INT_TYPE                  VARCHAR2(3 CHAR),
  DR_PERIOD_FREQ               VARCHAR2(2 CHAR),
  DR_NEXT_CYCLE_DATE           DATE,
  DR_INT_DAY                   NUMBER(2),
  DR_ACCT_LEVEL_INT_RATE       NUMBER(13,8),
  DR_SPREAD_RATE               NUMBER(13,8),
  PENALTY_MARGIN_RATE          NUMBER(8,3),
  DR_INT_CAP                   VARCHAR2(1 CHAR) DEFAULT 'Y',
  DR_INT_ACCRUED_CTD           NUMBER           DEFAULT 0,
  DR_INT_ACCRUED_MTD           NUMBER           DEFAULT 0,
  DR_INT_ACCRUED_YTD           NUMBER           DEFAULT 0,
  DR_INT_ACCRUED_CALC_CTD      NUMBER           DEFAULT 0,
  DR_INT_COLL_MTD              NUMBER           DEFAULT 0,
  DR_INT_COLL_CTD              NUMBER           DEFAULT 0,
  DR_INT_COLL_YTD              NUMBER           DEFAULT 0,
  DR_INT_COLL_LAST_YEAR        NUMBER           DEFAULT 0,
  DR_INT_UNPOSTED_CTD          NUMBER           DEFAULT 0,
  DR_INT_POSTED                NUMBER           DEFAULT 0,
  DR_INT_UNPOSTED              NUMBER           DEFAULT 0,
  DR_INT_ADJ                   NUMBER           DEFAULT 0,
  DR_INT_ADJ_MTD               NUMBER           DEFAULT 0,
  DR_INT_ADJ_CTD               NUMBER           DEFAULT 0,
  DR_INT_ADJ_YTD               NUMBER           DEFAULT 0,
  DR_INT_ADJ_CALC_CTD          NUMBER           DEFAULT 0,
  DR_INT_ADJ_POSTED            NUMBER           DEFAULT 0,
  DR_INT_ADJ_COLL_MTD          NUMBER           DEFAULT 0,
  DR_INT_ADJ_COLL_CTD          NUMBER           DEFAULT 0,
  DR_INT_ADJ_COLL_YTD          NUMBER           DEFAULT 0,
  DR_INT_ACCRUED_MTD_NOT_PAID  NUMBER           DEFAULT 0,
  DR_INT_ADJ_UNPOSTED_CTD      NUMBER           DEFAULT 0,
  DR_INT_PENALTY_CTD           NUMBER           DEFAULT 0,
  DR_INT_PENALTY_MTD           NUMBER           DEFAULT 0,
  DR_INT_ACCRUED               NUMBER           DEFAULT 0,
  DR_THIRD_PARTY_ACCT          NUMBER(12),
  DR_INT_CTRL_DATE             DATE,
  DR_LAST_CYCLE_DATE           DATE,
  DR_LAST_BACKDATE_ACCR        DATE,
  LAST_CHANGE_DATE             DATE,
  LAST_CHANGE_OFFICER          VARCHAR2(30 CHAR),
  FORCE_ACCR_DATE              DATE,
  FORCE_POSTING                VARCHAR2(1 CHAR),
  CR_INT_RATE_IND              VARCHAR2(1 CHAR),
  DR_INT_RATE_IND              VARCHAR2(1 CHAR),
  CR_PREV_LAST_CYCLE_DATE      DATE,
  CR_PREV_LAST_CYCLE_DATE2     DATE,
  TD_INT_END_DATE              DATE,
  TD_INT_NUM_DAYS              NUMBER,
  TD_INT_REM_DAYS              NUMBER,
  CR_INT_POSTED_CALC_CTD       NUMBER           DEFAULT 0,
  ACCT_CLOSE_PYMT_OPTION       VARCHAR2(1 CHAR),
  MONTHLY_BASIS                VARCHAR2(3 CHAR),
  CR_THIRD_CARD_PB_IND         VARCHAR2(1 CHAR),
  DR_THIRD_CARD_PB_IND         VARCHAR2(1 CHAR),
  CR_TAX_UNPOSTED              NUMBER           DEFAULT 0,
  CR_THIRD_CARD_NO             VARCHAR2(50 CHAR),
  DR_THIRD_CARD_NO             VARCHAR2(50 CHAR)
);