DROP TABLE CD_CARD_MAINACC;
CREATE TABLE CD_CARD_MAINACC (CARD_NO VARCHAR2(19 CHAR) NOT NULL, 
MAIN_ACC_NO VARCHAR2(50 CHAR), 
FLAG CHAR(1 CHAR), 
VALID_DATE VARCHAR2(8 CHAR), 
LAST_MODI_DATE VARCHAR2(8 CHAR), 
MODI_OPT_NO VARCHAR2(30 CHAR), 
PRODUCT_ID VARCHAR2(10 CHAR), 
CCY VARCHAR2(3 CHAR));
