DROP TABLE RB_TRAN_HIST;
CREATE TABLE RB_TRAN_HIST
(
  SEQ_NO                        NUMBER(12) CONSTRAINT RTH_NN1 NOT NULL,
  INTERNAL_KEY                  NUMBER(12),
  TRAN_DATE                     DATE CONSTRAINT RTH_NN3 NOT NULL,
  SOURCE_TYPE                   VARCHAR2(2 CHAR),
  TERMINAL_ID                   VARCHAR2(200 CHAR),
  BRANCH                        VARCHAR2(6 CHAR),
  OFFICER_ID                    VARCHAR2(30 CHAR),
  TRAN_TYPE                     VARCHAR2(4 CHAR),
  EFFECT_DATE                   DATE,
  POST_DATE                     DATE,
  REVERSAL_TRAN_TYPE            VARCHAR2(4 CHAR),
  REVERSAL_DATE                 DATE,
  PBK_UPD_FLAG                  VARCHAR2(1 CHAR) DEFAULT 'N',
  STMT_DATE                     DATE,
  TRAN_AMT                      NUMBER,
  REFERENCE_TYPE                VARCHAR2(4 CHAR),
  REFERENCE                     VARCHAR2(50 CHAR),
  REFERENCE_BANK                VARCHAR2(8 CHAR),
  FLOAT_DAYS                    NUMBER(2),
  PREVIOUS_BAL_AMT              NUMBER,
  ACTUAL_BAL_AMT                NUMBER,
  TFR_INTERNAL_KEY              NUMBER(12),
  TFR_SEQ_NO                    NUMBER(12),
  TRACE_ID                      NUMBER(12),
  CR_DR_MAINT_IND               VARCHAR2(1 CHAR),
  OVERRIDE_OFFICER              VARCHAR2(30 CHAR),
  REFERENCE_BRANCH              VARCHAR2(6 CHAR),
  TRAN_DESC                     VARCHAR2(30 CHAR),
  TIME_STAMP                    DATE,
  BR_SEQ_NO                     NUMBER,
  CD_CASH_FLOW_FLAG             VARCHAR2(1 CHAR),
  VALUE_DATE                    DATE,
  CCY                           VARCHAR2(3 CHAR),
  PROFIT_CENTRE                 VARCHAR2(12 CHAR),
  SOURCE_MODULE                 VARCHAR2(2 CHAR),
  BT_OFFICER_ID                 VARCHAR2(30 CHAR),
  BT_OVERRIDE_ID                VARCHAR2(30 CHAR),
  RECEIPT_NO                    VARCHAR2(20 CHAR),
  PRIMARY_SEQ_NO                NUMBER(12),
  RATE_TYPE                     VARCHAR2(3 CHAR),
  PURPOSE_CODE                  VARCHAR2(10 CHAR),
  SPEC_CODE                     VARCHAR2(10 CHAR),
  OTH_BANK_CODE                 VARCHAR2(12 CHAR),
  OTH_ACCT_NO                   VARCHAR2(50 CHAR),
  OTH_ACCT_DESC                 VARCHAR2(150 CHAR),
  OTH_ACCT_DESC2                VARCHAR2(150 CHAR),
  OTH_REFERENCE                 VARCHAR2(50 CHAR),
  OTH_SPEC_CODE                 VARCHAR2(10 CHAR),
  OTH_VALUE_DATE                DATE,
  MSG_CLIENT                    VARCHAR2(250 CHAR),
  TRAN_REF_NO                   VARCHAR2(50 CHAR),
  CLIENT_CROSS_REF              VARCHAR2(23 CHAR),
  TRN                           VARCHAR2(20 CHAR),
  SOURCE_REF_NO                 VARCHAR2(50 CHAR),
  OTH_AMT                       NUMBER,
  SOURCE_REF_TYPE               VARCHAR2(2 CHAR),
  SERV_CHARGE                   VARCHAR2(1 CHAR) DEFAULT 'N',
  CONS_SEQ_NO                   NUMBER,
  SORT_PRIORITY                 NUMBER(2),
  APPROVAL_DATE                 DATE,
  FORMAT                        VARCHAR2(10 CHAR),
  LAST_PROCESS_DATE             DATE,
  LAST_PROCESS_ERR              NUMBER(6),
  MSG_BANK                      VARCHAR2(150 CHAR),
  ORIG_SETTLEMENT_DATE          DATE,
  ORIG_TRAN_REF_NO              VARCHAR2(50 CHAR),
  STATUS_INFO                   VARCHAR2(2000 CHAR),
  NARRATIVE                     VARCHAR2(105 CHAR),
  TRAN_DATE_TIME                DATE,
  FH_SEQ_NO                     NUMBER,
  TRAN_ENTRY_DATE               DATE,
  INWD_SVC_SEQ                  NUMBER,
  SESSION_ID                    VARCHAR2(4 CHAR),
  APPROVING_OFFICER             VARCHAR2(30 CHAR),
  OVERRIDE_APPROVING_OFFICER    VARCHAR2(30 CHAR),
  PREFIX                        VARCHAR2(10 CHAR),
  SUB_STATUS                    VARCHAR2(1 CHAR),
  OUR_CORRESPONDENT             VARCHAR2(12 CHAR),
  ACCOUNT_BANK_CODE             VARCHAR2(12 CHAR),
  OTH_CORRESPONDENT             VARCHAR2(12 CHAR),
  OTH_ACCT_BANK_CODE            VARCHAR2(12 CHAR),
  ANSWERING_BANK_NO             VARCHAR2(12 CHAR),
  ANSWERING_BANK_CORRESPONDENT  VARCHAR2(12 CHAR),
  INITIAL_TRAN_REF_NO           VARCHAR2(50 CHAR),
  ACCOUNT_BRANCH                VARCHAR2(6 CHAR),
  NOSTRO_BRANCH                 VARCHAR2(6 CHAR),
  BORROWING_LENDING_RATE        NUMBER,
  TENOR                         NUMBER,
  MSG_CODE_OUR                  VARCHAR2(4 CHAR),
  MSG_CODE_OTHER                VARCHAR2(4 CHAR),
  VERIFICATION_OFFICER          VARCHAR2(30 CHAR),
  VERIFICATION_DATE             DATE,
  GL_TYPE                       VARCHAR2(1 CHAR),
  ORIG_CMT_CODE                 VARCHAR2(3 CHAR),
  BANK_CODE                     VARCHAR2(12 CHAR),
  ACCT_NO                       VARCHAR2(50 CHAR),
  ACCT_DESC                     VARCHAR2(150 CHAR),
  TRAN_CATEGORY                 VARCHAR2(1 CHAR),
  MESSAGE_FOR_INTRA_BANK        VARCHAR2(1 CHAR),
  ORIG_ACCT_DESC                VARCHAR2(150 CHAR),
  BANK_SEQ_NO                   VARCHAR2(20 CHAR),
  D2_REFERENCE                  VARCHAR2(50 CHAR),
  OTH_ACCT_TYPE                 VARCHAR2(3 CHAR),
  BAL_TYPE                      VARCHAR2(2 CHAR),
  BASE_ACCT_NO                  VARCHAR2(50 CHAR),
  OTH_BASE_ACCT_NO              VARCHAR2(50 CHAR),
  OTH_ACCT_CCY                  VARCHAR2(3 CHAR),
  AUTO_DR_OTH_BAL_TYPE          VARCHAR2(2 CHAR),
  BUSINESS_UNIT                 VARCHAR2(5 CHAR),
  CHEQUE_TYPE                   VARCHAR2(9 CHAR),
  CASH_ITEM                     VARCHAR2(4 CHAR),
  TRAN_NOTE                     VARCHAR2(50 CHAR),
  PRINT_CNT                     NUMBER,
  SUB_INTERNAL_KEY              NUMBER,
  SUB_ACCT_NO                   VARCHAR2(50 CHAR),
  ENTER_FLAG                    VARCHAR2(1 CHAR),
  TRAN_STATUS                   VARCHAR2(1 CHAR)
);