--
-- Create Schema Script 
--   Database Version   : 10.2.0.5.0 
--   TOAD Version       : 9.0.1.8 
--   DB Connect String  : 10.40.12.150:1521/netbank 
--   Schema             : WZMSHFIRMBANK 
--   Script Created by  : WZMSHCOMMON 
--   Script Created at  : 2016/10/11 16:14:43 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Tables: 50         Columns: 648        




@E:\WZMSHFIRMBANK\Tables\T_MSG_CONTENT.sql;
@E:\WZMSHFIRMBANK\Tables\T_INNER_CROSS_LIMIT_MONEY.sql;
@E:\WZMSHFIRMBANK\Tables\T_FIRM_DICTIONARY.sql;
@E:\WZMSHFIRMBANK\Tables\T_BANK_QUOTA.sql;
@E:\WZMSHFIRMBANK\Tables\T_USUAL_PAYEE.sql;
@E:\WZMSHFIRMBANK\Tables\T_TRANSFER.sql;
@E:\WZMSHFIRMBANK\Tables\T_TIME_DEMAND.sql;
@E:\WZMSHFIRMBANK\Tables\T_SEQ_REG.sql;
@E:\WZMSHFIRMBANK\Tables\T_RECEIPT_QUERY.sql;
@E:\WZMSHFIRMBANK\Tables\T_QUOTA_REG_LOG.sql;
@E:\WZMSHFIRMBANK\Tables\T_QUARTZ_JOB.sql;
@E:\WZMSHFIRMBANK\Tables\T_PURPOSE.sql;
@E:\WZMSHFIRMBANK\Tables\T_PAYOFF_ITEM.sql;
@E:\WZMSHFIRMBANK\Tables\T_PAYOFF.sql;
@E:\WZMSHFIRMBANK\Tables\T_PAYEE_CATALOG.sql;
@E:\WZMSHFIRMBANK\Tables\T_OPERATOR_MSG.sql;
@E:\WZMSHFIRMBANK\Tables\T_OPERATOR.sql;
@E:\WZMSHFIRMBANK\Tables\T_OPERATION_LOG.sql;
@E:\WZMSHFIRMBANK\Tables\T_NET_OPEN_LOG.sql;
@E:\WZMSHFIRMBANK\Tables\T_MENU_ROLE.sql;
@E:\WZMSHFIRMBANK\Tables\T_MENU_LINK.sql;
@E:\WZMSHFIRMBANK\Tables\T_MENU_CTRL.sql;
@E:\WZMSHFIRMBANK\Tables\T_MENU.sql;
@E:\WZMSHFIRMBANK\Tables\T_MAX_CASHPAY.sql;
@E:\WZMSHFIRMBANK\Tables\T_LOGIN_TICKET.sql;
@E:\WZMSHFIRMBANK\Tables\T_LOAN_REPAY.sql;
@E:\WZMSHFIRMBANK\Tables\T_LOAN.sql;
@E:\WZMSHFIRMBANK\Tables\T_JUMP_TICKET.sql;
@E:\WZMSHFIRMBANK\Tables\T_HOST_TRANS_CTRL.sql;
@E:\WZMSHFIRMBANK\Tables\T_FIRM.sql;
@E:\WZMSHFIRMBANK\Tables\T_CORE_AUDIT.sql;
@E:\WZMSHFIRMBANK\Tables\T_CONTR_TO_ACCT.sql;
@E:\WZMSHFIRMBANK\Tables\T_CONTR_ACCT_BIZ.sql;
@E:\WZMSHFIRMBANK\Tables\T_CONTRACT.sql;
@E:\WZMSHFIRMBANK\Tables\T_CHECK_RECEIPT.sql;
@E:\WZMSHFIRMBANK\Tables\T_BULLETIN.sql;
@E:\WZMSHFIRMBANK\Tables\T_BIZFLOW_CFG.sql;
@E:\WZMSHFIRMBANK\Tables\T_BF_LAST_ASSIGNEE.sql;
@E:\WZMSHFIRMBANK\Tables\T_BF_HISTORY_STEP.sql;
@E:\WZMSHFIRMBANK\Tables\T_BF_ENTRY.sql;
@E:\WZMSHFIRMBANK\Tables\T_BF_CURRENT_STEP.sql;
@E:\WZMSHFIRMBANK\Tables\T_BATCH_RUN_LOG.sql;
@E:\WZMSHFIRMBANK\Tables\T_AUTH_ROLE.sql;
@E:\WZMSHFIRMBANK\Tables\T_AUTH_BIZ.sql;
@E:\WZMSHFIRMBANK\Tables\T_AUTH_ACCOUNT.sql;
@E:\WZMSHFIRMBANK\Tables\T_AUTH.sql;
@E:\WZMSHFIRMBANK\Tables\T_APP_TICKET.sql;
@E:\WZMSHFIRMBANK\Tables\T_ACTION.sql;
@E:\WZMSHFIRMBANK\Tables\T_ACCT_AUDIT.sql;
@E:\WZMSHFIRMBANK\Tables\T_ACCOUNT.sql;
