CREATE TABLE T_ACCT_AUDIT
(
  ID_ACCT_AUDITING  NUMBER(6),
  UB_CODE           VARCHAR2(5 CHAR),
  SEQ               INTEGER,
  MIN_AMOUNT        NUMBER(17,2),
  NOTIFY_MODE       INTEGER                     DEFAULT 0,
  ISSUE_TIME        DATE,
  REVOKE_TIME       DATE,
  AUDIT_STATUS      VARCHAR2(1 CHAR),
  MOBILE            VARCHAR2(11 CHAR),
  CONTRACT_NUM      VARCHAR2(12 CHAR),
  AUDIT_TYPE        VARCHAR2(20 CHAR),
  ACCT_ID           VARCHAR2(32 CHAR),
  PHONE             VARCHAR2(20 CHAR),
  EMAIL             VARCHAR2(50 CHAR),
  NAME              VARCHAR2(20 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


