CREATE TABLE T_ACTION
(
  ACTION_UUID          VARCHAR2(32 CHAR),
  APP_ADDR             VARCHAR2(30 CHAR),
  APP_CODE             VARCHAR2(20 CHAR),
  APP_CONTEXT_ROOT     VARCHAR2(20 CHAR),
  APP_PORT             INTEGER,
  APP_TICKET           VARCHAR2(32 CHAR),
  CUST_ID              VARCHAR2(50 CHAR),
  CUST_ID_TYPE         VARCHAR2(20 CHAR),
  GEN_TIME             DATE,
  JUMP_TICKET          VARCHAR2(32 CHAR),
  LOGIN_TICKET         VARCHAR2(32 CHAR),
  REF_GEN_TIME         DATE,
  REF_TXN_TIME         DATE,
  REF_UPD_TIME         DATE,
  RESP_APP_TICKET      VARCHAR2(32 CHAR),
  RESP_CUST_ID         VARCHAR2(50 CHAR),
  RESP_CUST_ID_TYPE    VARCHAR2(20 CHAR),
  RESP_JUMP_TICKET     VARCHAR2(32 CHAR),
  TARGET_APP_CODE      VARCHAR2(20 CHAR),
  TARGET_CUST_ID       VARCHAR2(50 CHAR),
  TARGET_CUST_ID_TYPE  VARCHAR2(20 CHAR),
  TXN_CODE             VARCHAR2(20 CHAR),
  TXN_TICKET           VARCHAR2(32 CHAR),
  TXN_TIME             DATE,
  UPD_TIME             DATE,
  VERSION              INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


