CREATE TABLE T_ACCOUNT
(
  ID_ACCOUNT     NUMBER(6),
  UB_CODE        VARCHAR2(5 CHAR),
  NCID           VARCHAR2(15 CHAR),
  BRANCH_ID      VARCHAR2(5 CHAR),
  CURRENCY       VARCHAR2(2 CHAR),
  ACCT_TYPE      VARCHAR2(1 CHAR)               DEFAULT '0',
  ACCT_STATUS    VARCHAR2(1 CHAR),
  CAN_OVERDRAFT  VARCHAR2(1 CHAR),
  UPDATE_TIME    DATE,
  CREATE_TIME    DATE,
  ACCT_ID        VARCHAR2(32 CHAR),
  EXCH_CITY      VARCHAR2(30 CHAR),
  NAME           VARCHAR2(60 CHAR),
  ALIAS          VARCHAR2(60 CHAR),
  BANK_NAME      VARCHAR2(60 CHAR),
  PROGRAM_NO     VARCHAR2(20 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


