CREATE TABLE T_APP_TICKET
(
  APP_TICKET    VARCHAR2(32 CHAR),
  APP_CODE      VARCHAR2(20 CHAR),
  CUST_ID       VARCHAR2(50 CHAR),
  CUST_ID_TYPE  VARCHAR2(20 CHAR),
  GEN_TIME      DATE,
  LOGIN_TICKET  VARCHAR2(32 CHAR),
  REF_GEN_TIME  DATE,
  VERSION       INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


