CREATE TABLE T_AUTH
(
  ID_AUTH      NUMBER(6),
  UB_CODE      VARCHAR2(5 CHAR),
  NCID         VARCHAR2(15 CHAR),
  OID          VARCHAR2(8 CHAR),
  ISSUE_TIME   DATE,
  REVOKE_TIME  DATE,
  AUTH_STATUS  INTEGER                          DEFAULT 0,
  PRE_AUTH_ID  INTEGER,
  UPDATE_TIME  DATE,
  CREATE_TIME  DATE,
  DEAL_QUOTA   NUMBER(17,2),
  DAY_QUOTA    NUMBER(17,2),
  VERSION      INTEGER,
  AUTH_TYPE    VARCHAR2(20 CHAR),
  MEMO         VARCHAR2(30 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


