CREATE TABLE T_BANK_QUOTA
(
  UB_CODE                 CHAR(5 CHAR),
  DEAL_LIMITED_AMT        NUMBER,
  DAY_LIMITED_AMT         NUMBER,
  PAYOFF_MONTH_AMT        NUMBER,
  DEAL_AUTH_AMT           NUMBER,
  AVAIL_DEAL_LIMITED_AMT  NUMBER,
  AVAIL_DAY_LIMITED_AMT   NUMBER,
  AVAIL_PAYOFF_MONTH_AMT  NUMBER,
  AVAIL_DEAL_AUTH_AMT     NUMBER,
  START_DATE              DATE,
  CREATE_TIME             DATE,
  UPDATE_TIME             DATE,
  STATUS                  CHAR(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


