CREATE TABLE T_BATCH_RUN_LOG
(
  I_BATCH_TASK_LOG  NUMBER(6),
  RUN_TIME          DATE,
  RUN_RESULT        VARCHAR2(1 CHAR),
  RUN_IP            VARCHAR2(20 CHAR),
  TASK_NAME         VARCHAR2(30 CHAR),
  EXCEPT_MSG        VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


