CREATE TABLE T_BF_ENTRY
(
  ID_ENTRY        NUMBER(6),
  UB_CODE         VARCHAR2(5 CHAR),
  NCID            VARCHAR2(15 CHAR),
  OWNER           VARCHAR2(8 CHAR),
  START_TIME      DATE,
  UPDATE_TIME     DATE,
  DUE_DATE        DATE,
  BIZFLOW_STATUS  VARCHAR2(1 CHAR),
  VERSION         INTEGER,
  FLOW_NAME       VARCHAR2(20 CHAR),
  BIZ_FLOW_TYPE   VARCHAR2(20 CHAR),
  BIZ_CODE        VARCHAR2(30 CHAR),
  ACCT_ID         VARCHAR2(32 CHAR),
  MESSAGE         VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


