CREATE TABLE T_BF_LAST_ASSIGNEE
(
  ID_LAST_ASSIGNEE  NUMBER(6),
  UB_CODE           VARCHAR2(5 CHAR),
  OID               VARCHAR2(8 CHAR),
  STEP_ID           INTEGER,
  ASSIGNEE_OID      VARCHAR2(8 CHAR),
  CREATE_TIME       DATE,
  UPDATE_TIME       DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


