CREATE TABLE T_BF_HISTORY_STEP
(
  ID_CURRENT_STEP  NUMBER(6),
  ID_ENTRY         INTEGER,
  STEP_ID          INTEGER,
  OWNER            VARCHAR2(8 CHAR),
  ACTION_ID        INTEGER,
  CALLER           VARCHAR2(8 CHAR),
  START_TIME       DATE,
  DUE_DATE         DATE,
  FINISH_TIME      DATE,
  STEP_STATUS      VARCHAR2(20 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


