CREATE TABLE T_BIZFLOW_CFG
(
  ID_BIZFLOW_CFG  NUMBER(6),
  UB_CODE         VARCHAR2(5 CHAR),
  NCID            VARCHAR2(15 CHAR),
  CFG_STATUS      VARCHAR2(1 CHAR),
  ISSUE_TIME      DATE,
  REVOKE_TIME     DATE,
  CREATE_TIME     DATE,
  UPDATE_TIME     DATE,
  BIZ_TYPE        VARCHAR2(30 CHAR),
  BIZ_FLOW_MODE   VARCHAR2(30 CHAR),
  FLOW_ROLES      VARCHAR2(255 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


