CREATE TABLE T_CHECK_RECEIPT
(
  ID_CHK_RETURN   NUMBER(6),
  UB_CODE         VARCHAR2(5 CHAR),
  NCID            VARCHAR2(15 CHAR),
  OID             VARCHAR2(8 CHAR),
  ACCT_NO         VARCHAR2(32 CHAR),
  ACCT_NAME       VARCHAR2(60 CHAR),
  CHK_MONTH       VARCHAR2(7 CHAR),
  CURRENCY        VARCHAR2(2 CHAR),
  BANK_BALANCE    NUMBER(17,2),
  ACCORDANT       VARCHAR2(1 CHAR),
  CHK_BALANCE     NUMBER(17,2),
  CHECK_RESULT    VARCHAR2(50 CHAR),
  CAUSE           VARCHAR2(200 CHAR),
  LINKMAN         VARCHAR2(50 CHAR),
  TEL             VARCHAR2(20 CHAR),
  CHK_DATE        DATE,
  CHK_ADJUST_AMT  NUMBER(17,2),
  BK_ADJUST_AMT   NUMBER(17,2),
  SEND_TIME       DATE,
  UPDATE_TIME     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


