CREATE TABLE T_CONTRACT
(
  ID_CONTRACT       NUMBER(6),
  UB_CODE           VARCHAR2(5 CHAR),
  NCID              VARCHAR2(15 CHAR),
  CONTR_STATUS      INTEGER                     DEFAULT 0,
  CREATE_TIME       DATE,
  ISSUE_TIME        DATE,
  REVOKE_TIME       DATE,
  PRE_ID_CONTRACT   INTEGER,
  COMMON_YES_NO_1   VARCHAR2(1 CHAR),
  COMMON_YES_NO_2   VARCHAR2(1 CHAR),
  COMMON_INT        INTEGER,
  DEAL_LIMITED_AMT  NUMBER(17,2),
  DAY_LIMITED_AMT   NUMBER(17,2),
  PAYOFF_MONTH_AMT  NUMBER(17,2),
  UPDATE_TIME       DATE,
  VERSION           INTEGER,
  APPLY_MODE        VARCHAR2(10 CHAR),
  PRE_CONTRACT_NO   VARCHAR2(20 CHAR),
  CONTRACT_NO       VARCHAR2(20 CHAR),
  CONTRACT_TYPE     VARCHAR2(20 CHAR),
  ACCT_ID           VARCHAR2(32 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


