CREATE TABLE T_CORE_AUDIT
(
  ID_CORE_AUDIT  NUMBER(6),
  AUDIT_TYPE     VARCHAR2(1 CHAR),
  UBCODE         VARCHAR2(5 CHAR),
  CORE_STATUS    INTEGER,
  APPROVAL_NUM   VARCHAR2(6 CHAR),
  CREATE_TIME    DATE,
  UPDATE_TIME    DATE,
  NCID           VARCHAR2(15 CHAR),
  ACCT_ID        VARCHAR2(32 CHAR),
  BIZ_REATE_ID   VARCHAR2(20 CHAR),
  BIZ_TYPE       VARCHAR2(30 CHAR),
  AUDIT_CAUSE    VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


