CREATE TABLE T_HOST_TRANS_CTRL
(
  ID_HOST_TRANS_CTRL  NUMBER(6),
  SRVRTID             VARCHAR2(12 CHAR),
  TYPE                VARCHAR2(20 CHAR),
  DUE_DATE            DATE,
  STATUS              INTEGER,
  APPROVAL_NUM        VARCHAR2(12 CHAR),
  CREATE_DATE         DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


