CREATE TABLE T_JUMP_TICKET
(
  JUMP_TICKET   VARCHAR2(32 CHAR),
  APP_CODE      VARCHAR2(20 CHAR),
  ATTACHMENT    VARCHAR2(255 CHAR),
  CUST_ID       VARCHAR2(50 CHAR),
  CUST_ID_TYPE  VARCHAR2(20 CHAR),
  DEADLINE      DATE,
  GEN_TIME      DATE,
  LOGIN_TICKET  VARCHAR2(32 CHAR),
  REF_DEADLINE  DATE,
  REF_GEN_TIME  DATE,
  VERSION       INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


