CREATE TABLE T_LOAN
(
  SRVRTID         VARCHAR2(12 CHAR),
  ID_ENTRY        INTEGER,
  UB_CODE         VARCHAR2(5 CHAR),
  NCID            VARCHAR2(15 CHAR),
  VOUCHER_TYPE    VARCHAR2(2 CHAR),
  VOUCHER_REF     VARCHAR2(12 CHAR),
  ACCT_NO         VARCHAR2(32 CHAR),
  LOAN_DATE       DATE,
  END_DATE        DATE,
  CCY             VARCHAR2(2 CHAR),
  PURPOSE         VARCHAR2(50 CHAR),
  LOAN_KEY        VARCHAR2(12 CHAR),
  REPAY_MODE      VARCHAR2(1 CHAR),
  AMOUNT          NUMBER(17,2),
  LOAN_NO         VARCHAR2(50 CHAR),
  TRANS_STATUS    VARCHAR2(1 CHAR),
  CREATE_TIME     DATE,
  UPDATE_TIME     DATE,
  SEND_TIME       DATE,
  RECV_TIME       DATE,
  MSG_ID          INTEGER,
  MSG             VARCHAR2(100 CHAR),
  BANK_TRACE_ID   VARCHAR2(30 CHAR),
  SEND_BATCH_ID   VARCHAR2(12 CHAR),
  VERSION         INTEGER,
  CLIENT_REF_NUM  VARCHAR2(30 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


