CREATE TABLE T_LOGIN_TICKET
(
  LOGIN_TICKET      VARCHAR2(32 CHAR),
  APP_CODE          VARCHAR2(20 CHAR),
  APP_CONTEXT_ROOT  VARCHAR2(20 CHAR),
  CUST_ID           VARCHAR2(50 CHAR),
  CUST_ID_TYPE      VARCHAR2(20 CHAR),
  GEN_TIME          DATE,
  LOGOUT_TIME       DATE,
  REF_GEN_TIME      DATE,
  REF_LOGOUT_TIME   DATE,
  REF_UPD_TIME      DATE,
  UPD_TIME          DATE,
  VALID_FLAG        VARCHAR2(1 CHAR),
  VERSION           INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


