CREATE TABLE T_LOAN_REPAY
(
  SRVRTID         CHAR(12 CHAR),
  ID_ENTRY        INTEGER,
  UB_CODE         CHAR(5 CHAR),
  NCID            VARCHAR2(15 CHAR),
  VOUCHER_TYPE    VARCHAR2(2 CHAR),
  VOUCHER_REF     VARCHAR2(12 CHAR),
  LOAN_NO         CHAR(50 CHAR),
  LOAN_KEY        CHAR(12 CHAR),
  REPAY_TYPE      CHAR(2 CHAR),
  CCY             CHAR(2 CHAR),
  PRE_AMOUNT      NUMBER(17,2),
  REPAY_AMOUNT    NUMBER(17,2),
  PRE_FLAG        CHAR(1 CHAR),
  REPAY_FLAG      CHAR(1 CHAR),
  ACCT_NO         VARCHAR2(32 CHAR),
  TRANS_STATUS    VARCHAR2(1 CHAR),
  CREATE_TIME     DATE,
  UPDATE_TIME     DATE,
  SEND_TIME       DATE,
  RECV_TIME       DATE,
  MSG_ID          INTEGER,
  MSG             VARCHAR2(100 CHAR),
  BANK_TRACE_ID   VARCHAR2(30 CHAR),
  SEND_BATCH_ID   VARCHAR2(12 CHAR),
  VERSION         INTEGER,
  CLIENT_REF_NUM  VARCHAR2(30 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


