CREATE TABLE T_MAX_CASHPAY
(
  ID_MAX_CASHPAY  NUMBER(6),
  UB_CODE         VARCHAR2(5 CHAR),
  MAX_AMT         NUMBER(17,2),
  LIMIT_STATUS    VARCHAR2(1 CHAR),
  CREATE_TIME     DATE,
  UPDATE_TIME     DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


