CREATE TABLE T_MENU_LINK
(
  ID_MENU_LINK  NUMBER(6),
  SEQ           INTEGER,
  FUN_ID        VARCHAR2(20 CHAR),
  TARGET        VARCHAR2(20 CHAR),
  LINK_NAME     VARCHAR2(50 CHAR),
  URL           VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


