CREATE TABLE T_MENU
(
  ID_MENU      INTEGER,
  PARENT_ID    INTEGER,
  IS_END       VARCHAR2(1 CHAR),
  SEQ          INTEGER,
  STATUS       INTEGER                          DEFAULT 1,
  IS_USUALLY   VARCHAR2(1 CHAR),
  IS_SHORTCUT  VARCHAR2(1 CHAR),
  IS_INCLUDE   VARCHAR2(1 CHAR),
  CREATE_TIME  DATE,
  UPDATE_TIME  DATE,
  FUN_ID       VARCHAR2(20 CHAR),
  TARGET       VARCHAR2(20 CHAR),
  MENU_NAME    VARCHAR2(50 CHAR),
  BIZ_CODES    VARCHAR2(60 CHAR),
  FIRM_TYPES   VARCHAR2(60 CHAR),
  DESCRIPTION  VARCHAR2(100 CHAR),
  URL          VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


