CREATE TABLE T_MSG_CONTENT
(
  ID_MSG_CONTENT  NUMBER(6),
  SCOPE_TYPE      VARCHAR2(1 CHAR),
  URGENT          VARCHAR2(1 CHAR),
  CONTENT_STATUS  VARCHAR2(1 CHAR),
  CREATE_TIME     DATE,
  SEND_TIME       DATE,
  SCOPE_CODE      VARCHAR2(32 CHAR),
  SUBMITOR        VARCHAR2(20 CHAR),
  SENDER          VARCHAR2(20 CHAR),
  TITLE           VARCHAR2(100 CHAR),
  CONTENT         CLOB
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


