CREATE TABLE T_NET_OPEN_LOG
(
  ID_NET_OPEN_LOG  NUMBER(6),
  LOG_TYPE         VARCHAR2(1 CHAR),
  OPEN_STATUS      VARCHAR2(1 CHAR),
  UB_CODE          VARCHAR2(5 CHAR),
  BRANCH_ID        VARCHAR2(5 CHAR),
  OPER_TIME        DATE,
  BANK_TRACE_ID    VARCHAR2(12 CHAR),
  NCID             VARCHAR2(15 CHAR),
  FIRM_NAME        VARCHAR2(60 CHAR),
  ACCT_ID          VARCHAR2(32 CHAR),
  ACCT_NAME        VARCHAR2(60 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


