CREATE TABLE T_OPERATOR_MSG
(
  ID_OPERATOR_MSG  NUMBER(6),
  ID_MSG_CONTENT   INTEGER,
  MSG_STATUS       VARCHAR2(1 CHAR),
  UB_CODE          VARCHAR2(5 CHAR),
  OID              VARCHAR2(8 CHAR),
  NCID             VARCHAR2(15 CHAR),
  UPDATE_TIME      DATE,
  CREATE_TIME      DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


