CREATE TABLE T_OPERATOR
(
  ID_OPERATOR     NUMBER(6),
  OID             VARCHAR2(8 CHAR),
  UB_CODE         VARCHAR2(5 CHAR),
  NCID            VARCHAR2(15 CHAR),
  OPER_TYPE       VARCHAR2(1 CHAR),
  OPER_STATUS     VARCHAR2(1 CHAR),
  PWD_COUNT       INTEGER,
  ID_CERT         INTEGER,
  GENDER          VARCHAR2(1 CHAR),
  LAST_SUCC_TIME  DATE,
  LAST_FAIL_TIME  DATE,
  UPDATE_TIME     DATE,
  CREATE_TIME     DATE,
  MOBILE          VARCHAR2(11 CHAR),
  ID_TYPE         VARCHAR2(30 CHAR),
  ID_NO           VARCHAR2(20 CHAR),
  POSITION        VARCHAR2(30 CHAR),
  PHONE           VARCHAR2(20 CHAR),
  LOGIN_NAME      VARCHAR2(20 CHAR),
  PASSWORD        VARCHAR2(32 CHAR),
  DEPARTMENT      VARCHAR2(50 CHAR),
  EMAIL           VARCHAR2(50 CHAR),
  OPER_NAME       VARCHAR2(60 CHAR),
  ALT_CAUSE       VARCHAR2(60 CHAR),
  FIRST_LOGIN     VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


