CREATE TABLE T_OPERATION_LOG
(
  ID_ACT_LOG  NUMBER(6),
  UB_CODE     VARCHAR2(5 CHAR),
  NCID        VARCHAR2(15 CHAR),
  OID         VARCHAR2(8 CHAR),
  ACT_TIME    DATE,
  CLIENT_IP   VARCHAR2(20 CHAR),
  ACT_TYPE    VARCHAR2(50 CHAR),
  CONTENT     VARCHAR2(500 CHAR),
  EGENT       VARCHAR2(500 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


