CREATE TABLE T_PAYOFF
(
  SRVRTID         VARCHAR2(12 CHAR),
  ID_ENTRY        INTEGER,
  UB_CODE         VARCHAR2(5 CHAR),
  NCID            VARCHAR2(15 CHAR),
  VOUCHER_TYPE    VARCHAR2(2 CHAR),
  VOUCHER_REF     VARCHAR2(8 CHAR),
  EXPECT_DATE     DATE,
  TOTAL_AMOUNT    NUMBER(17,2),
  TOTAL_COUNT     INTEGER,
  IS_VERIFY       VARCHAR2(1 CHAR),
  CREATE_TIME     DATE,
  SEND_BATCH_ID   VARCHAR2(12 CHAR),
  SEND_TIME       DATE,
  RECV_TIME       DATE,
  MSG_ID          INTEGER,
  SUCC_AMOUNT     NUMBER(17,2),
  SUCC_COUNT      INTEGER,
  FAIL_AMOUNT     NUMBER(17,2),
  FAIL_COUNT      INTEGER,
  BRIEF_CODE      VARCHAR2(3 CHAR),
  UPDATE_TIME     DATE,
  VERSION         INTEGER,
  TRANS_STATUS    VARCHAR2(1 CHAR),
  FROM_ACCT_ID    VARCHAR2(32 CHAR),
  CLIENT_REF_NUM  VARCHAR2(30 CHAR),
  BANK_TRACE_ID   VARCHAR2(30 CHAR),
  PURPOSE         VARCHAR2(200 CHAR),
  MSG             VARCHAR2(100 CHAR),
  FROM_ACCT_NAME  VARCHAR2(60 CHAR),
  MEMO            VARCHAR2(100 CHAR),
  TITLE           VARCHAR2(60 CHAR),
  PROGRAM_NO      VARCHAR2(20 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


