CREATE TABLE T_PAYOFF_ITEM
(
  ID_PAYOFF_ITEM  NUMBER(6),
  SRVRTID         VARCHAR2(12 CHAR),
  SEQ             INTEGER,
  AMOUNT          NUMBER(17,2),
  MSG_ID          INTEGER,
  CREATE_TIME     DATE,
  UPDATE_TIME     DATE,
  EID             VARCHAR2(10 CHAR),
  ACCT_ID         VARCHAR2(32 CHAR),
  MSG             VARCHAR2(50 CHAR),
  ACCT_NAME       VARCHAR2(60 CHAR),
  SEND_MAIL       VARCHAR2(50 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


