CREATE TABLE T_PAYEE_CATALOG
(
  ID_PAYEE_CATALOG  NUMBER(6),
  UB_CODE           VARCHAR2(5 CHAR),
  NCID              VARCHAR2(15 CHAR),
  PAYEE_TYPE        INTEGER,
  SEQ               INTEGER,
  CREATE_TIME       DATE,
  UPDATE_TIME       DATE,
  NAME              VARCHAR2(30 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


