CREATE TABLE T_PURPOSE
(
  ID_PURPOSE    NUMBER(6),
  UB_CODE       VARCHAR2(5 CHAR),
  OID           VARCHAR2(8 CHAR),
  NCID          VARCHAR2(15 CHAR),
  HIT_COUNT     INTEGER,
  PURPOSE_TYPE  INTEGER,
  CREATE_TIME   DATE,
  UPDATE_TIME   DATE,
  PURPOSE       VARCHAR2(200 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


