CREATE TABLE T_QUARTZ_JOB
(
  JOB_NAME            VARCHAR2(32 CHAR),
  FINISH_TIME         DATE,
  FIRE_TIME           DATE,
  NEXT_FIRE_TIME      DATE,
  REF_FINISH_TIME     DATE,
  REF_FIRE_TIME       DATE,
  REF_NEXT_FIRE_TIME  DATE,
  VERSION             INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


