CREATE TABLE T_QUOTA_REG_LOG
(
  ID_QUOTA_REG          NUMBER(6),
  UB_CODE               VARCHAR2(5 CHAR),
  NCID                  VARCHAR2(15 CHAR),
  QUOTA_TYPE            VARCHAR2(1 CHAR),
  ACCT_ID               VARCHAR2(32 CHAR),
  OID                   VARCHAR2(8 CHAR),
  ID_AUTH               VARCHAR2(10 CHAR),
  BIZ_DATE              DATE,
  DAY_UESED_AMT         NUMBER(17,2)            DEFAULT 0.00,
  MONTH_USED_PAYOFF     NUMBER(17,2)            DEFAULT 0.00,
  MONTH_USED_AMT        NUMBER(17,2)            DEFAULT 0.00,
  DAY_REMAIN_AMT        NUMBER(17,2)            DEFAULT 0.00,
  CREATE_TIME           DATE,
  UPDATE_TIME           DATE,
  INNER_DAY_UESED_AMT   NUMBER(17,2)            DEFAULT 0.00,
  CROSS_DAY_UESED_AMT   NUMBER(17,2)            DEFAULT 0.00,
  INNER_DAY_REMAIN_AMT  NUMBER(17,2)            DEFAULT 0.00,
  CROSS_DAY_REMAIN_AMT  NUMBER(17,2)            DEFAULT 0.00
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


