CREATE TABLE T_RECEIPT_QUERY
(
  ID_RECEIPT_QUERY  NUMBER(6),
  UB_CODE           VARCHAR2(5 CHAR),
  SRVRTID           VARCHAR2(12 CHAR),
  CREATE_TIME       DATE,
  QUERY_NUM         VARCHAR2(10 CHAR),
  RECEIPT_TYPE      VARCHAR2(20 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


