CREATE TABLE T_SEQ_REG
(
  I_SEQ_REG    NUMBER(6),
  HI_CTR       INTEGER,
  LO_CTR       INTEGER,
  SYNC_FLAG    INTEGER,
  CREATE_TIME  DATE,
  UPDATE_TIME  DATE,
  SECTION      VARCHAR2(10 CHAR),
  SEQ_TYPE     VARCHAR2(30 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


