CREATE TABLE T_TIME_DEMAND
(
  SRVRTID           VARCHAR2(12 CHAR),
  PARENT_ID         VARCHAR2(12 CHAR),
  ID_ENTRY          INTEGER,
  UB_CODE           VARCHAR2(5 CHAR),
  NCID              VARCHAR2(15 CHAR),
  VOUCHER_TYPE      VARCHAR2(2 CHAR),
  VOUCHER_REF       VARCHAR2(8 CHAR),
  AMOUNT            NUMBER(17,2),
  ACTION_TYPE       INTEGER,
  SUBJECT           VARCHAR2(6 CHAR),
  RATION_CODE       VARCHAR2(3 CHAR),
  RATIO             NUMBER(11,7),
  BOOK_DATE         DATE,
  BALANCE           NUMBER(17,2),
  OPEN_TIME         DATE,
  MATURITY_DATE     DATE,
  CREATE_TIME       DATE,
  UPDATE_TIME       DATE,
  TRANS_STATUS      VARCHAR2(1 CHAR),
  SEND_BATCH_ID     VARCHAR2(12 CHAR),
  SEND_TIME         DATE,
  RECV_TIME         DATE,
  MSG_ID            INTEGER,
  VERSION           INTEGER,
  TERM_TYPE         VARCHAR2(5 CHAR),
  CONTINUE_TERM     VARCHAR2(5 CHAR),
  FINANCING_TYPE    VARCHAR2(20 CHAR),
  DEMAND_ACCT_ID    VARCHAR2(32 CHAR),
  DEMAND_ACCT_NAME  VARCHAR2(60 CHAR),
  CALL_NUM          VARCHAR2(30 CHAR),
  FIXED_ACCT_ID     VARCHAR2(32 CHAR),
  FIXED_ACCT_MAME   VARCHAR2(60 CHAR),
  BANK_TRACE_ID     VARCHAR2(30 CHAR),
  MSG               VARCHAR2(100 CHAR),
  PRINTED           VARCHAR2(1 CHAR),
  CLIENT_REF_NUM    VARCHAR2(30 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


