CREATE TABLE T_USUAL_PAYEE
(
  ID_USUAL_PAYEE  NUMBER(6),
  UB_CODE         VARCHAR2(5 CHAR),
  NCID            VARCHAR2(15 CHAR),
  PAYEE_TYPE      INTEGER,
  SEQ             INTEGER,
  UPDATE_TIME     DATE,
  CREATE_TIME     DATE,
  INTRA_CITY      VARCHAR2(1 CHAR),
  INTRA_BANK      VARCHAR2(1 CHAR),
  CONTACT_MOBILE  VARCHAR2(11 CHAR),
  BANK_NUM        VARCHAR2(12 CHAR),
  CONTACT_NAME    VARCHAR2(20 CHAR),
  CATALOG         VARCHAR2(30 CHAR),
  EXCH_CITY       VARCHAR2(30 CHAR),
  ACCT_ID         VARCHAR2(32 CHAR),
  ALIAS_NAME      VARCHAR2(50 CHAR),
  CONTACT_EMAIL   VARCHAR2(50 CHAR),
  BANK_NAME       VARCHAR2(60 CHAR),
  NAME            VARCHAR2(60 CHAR),
  URGENT_LEVEL    VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


