prompt PL/SQL Developer import file
prompt Created on 2017Äê11ÔÂ9ÈÕ by saasuser1
set feedback off
set define off
prompt Disabling triggers for CB_USER_INF...
alter table CB_USER_INF disable all triggers;
prompt Loading CB_USER_INF...
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004668', '000018', 'ÌïÖÐÀ¼', null, null, null, '13886672426', null, '00010', 0, '1', '0', '0', null, null, null, '13886672426', null, null, 'wjFPJMBwfT0mZEyjZmM7VtvxdCRLM0qH', null, '1103', null, null, null, '422723196004020026');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004668', '000019', 'Ð¤ÓñÃ·', null, null, null, '15897573901', null, '00010', 0, '1', '0', '0', null, null, null, '15897573901', null, null, 'wjFPJMBwfT0mZEyjZmM7VtvxdCRLM0qH', null, '1103', null, null, null, '420526197911030026');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006055', '000046', '¹Åè¤', null, null, null, '13972001595', null, '00000', 0, '1', '0', '0', null, null, null, '13972001595', null, null, 'AYsH3c/HKbroR2lrjJzHaINZ4MMdm3As', null, '1103', null, null, null, '422723196809223146');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006055', '000047', '²Ì´ó¾ü', null, null, null, '13972024902', null, '00000', 0, '1', '0', '0', null, null, null, '13972024902', null, null, 'AYsH3c/HKbroR2lrjJzHaINZ4MMdm3As', null, '1103', null, null, null, '422723196612193131');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000191', '000052', 'Ñ¦·¼·¼', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'PIcMRE<OKpEHTAiZe3f<wYblg8d<wIvs', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000191', '000054', 'Íò¿¡·æ', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'PIcMRE<OKpEHTAiZe3f<wYblg8d<wIvs', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000354', '000059', 'ÁõÄÈ', null, null, null, '13477831666', null, '00000', 0, '1', '0', '0', null, null, null, '13477831666', null, null, 'NW6z5TuvzVPrZD0jeUF/qY1LORO0wbib', null, '1103', null, null, null, '420583198710210049');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000354', '000060', '¶¡Ð¡ÁÖ', null, null, null, '13972044808', null, '00000', 0, '1', '0', '0', null, null, null, '13972044808', null, null, 'sUEwkVU<ELlO3UGm5pxVG9QhwFm7SjMo', null, '1103', null, null, null, '422723197512090412');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006093', '000065', 'YFZ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'cmDRjeex4djoR2lrjJzHaFjpjNVzV2JD', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006093', '000067', 'FZ', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'cmDRjeex4djoR2lrjJzHaFjpjNVzV2JD', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005813', '000117', 'ÀîÁ¦ÇÚ', null, null, null, '13477857006', null, '00000', 0, '1', '0', '0', null, null, null, '13477857006', null, null, 'R5hkM6sFK1nCKRSlr9LgWBMHBNA1232o', null, '1103', null, null, null, '422723196705072240');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005813', '000118', 'ÐíÖÒ¹ó', null, null, null, '13986789716', null, '00000', 0, '1', '0', '0', null, null, null, '13986789716', null, null, 'R5hkM6sFK1nCKRSlr9LgWBMHBNA1232o', null, '1103', null, null, null, '422723196412032296');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005813', '000119', 'ÀîÁ¦ÇÚ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'cmCUjv2<OrgdFfWpnvylaopw73S49Ji9', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007745', '000123', 'Ðì´ºÑÞ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'hrbyVEhLe0F3Dl3oX9xo9BMHBNA1232o', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007745', '000124', 'Ò×¹ú', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'hrbyVEhLe0F3Dl3oX9xo9BMHBNA1232o', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004977', '000132', '¶ÅÄÝÄÈ', null, null, null, '18671774277', null, '10000', 0, '1', '0', '0', null, null, 'M', '18671774277', null, null, 'pBj3Qep1lJuRof4jWrFwonrapB9H1XTz', null, '1103', null, null, null, '420583198305010748');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004977', '000133', '¶ÅÀÚ', null, null, null, '18677214688', null, '00110', 1, '1', '0', '0', null, null, 'M', '18677214688', null, null, 'pBj3Qep1lJuRof4jWrFwonrapB9H1XTz', null, '1103', null, null, null, '420583198019160776');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008232', '000142', 'ÑîÇà', null, null, null, '15871571537', null, '00010', 0, '1', '0', '0', null, null, null, '15871571537', null, null, '9lgCC1w24RE9nyFrW0jDiG6XsERvfuIT', null, '1103', null, null, null, '420583198504250023');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008232', '000143', '´úºìÐÇ', null, null, null, '13308600688', null, '00010', 0, '1', '0', '0', null, null, null, '13308600688', null, null, '9lgCC1w24RE9nyFrW0jDiG6XsERvfuIT', null, '1103', null, null, null, '422723196601041917');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002249', '000146', 'ÕÔÀö»ª', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, '/nQW<x<E7vR6IsaAjiFssFcL0nNnCnDU', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002249', '000147', 'ÕÔÉú·ï', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, '/nQW<x<E7vR6IsaAjiFssFcL0nNnCnDU', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002378', '000153', 'Ê©Ë¼', null, null, null, '18608606761', null, '00000', 0, '1', '0', '0', null, null, null, '18608606761', null, null, 'oJ0CPlLBl1H6r00MH<cAOBMHBNA1232o', null, '1103', null, null, null, '420525198610140027');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002378', '000154', 'Áõ²¨', null, null, null, '15871610276', null, '00000', 0, '1', '0', '0', null, null, null, '15871610276', null, null, '99mHhrjsMoiJYi6lRbNvWimQ58fhob6m', null, '1103', null, null, null, '420521197208260063');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000398', '000162', 'ÁºÂ××£', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, '6OrEamPPtpCCAVzjWaahMmLpLzFZPezR', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002378', '000163', 'Ê©Ë¼', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, '99mHhrjsMoiJYi6lRbNvWimQ58fhob6m', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002378', '000164', 'Áõ²¨', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, '99mHhrjsMoiJYi6lRbNvWimQ58fhob6m', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006281', '000167', 'ÀîÏÈ±ø', null, null, null, '13986777722', null, '00010', 0, '1', '0', '0', null, null, null, '13986777722', null, null, 'Ox4fsGtZ1L67FmSiLiM0nIphIFPjQ9s5', null, '1103', null, null, null, '422723196502160793');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006281', '000168', 'Îâ¾²', null, null, null, '13682344493', null, '00010', 0, '1', '0', '0', null, null, null, '13682344493', null, null, 'lk9WbmeBoCG7FmSiLiM0nIphIFPjQ9s5', null, '1103', null, null, null, '422723197111110021');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008503', '000175', '½ðÓñÆ¼', null, null, null, '13972044886', null, '00010', 0, '1', '0', '0', null, null, null, '13972044886', null, null, '7qShW2vwFXfbJJUq/xXo7Xq//aBv7c3l', null, '1103', null, null, null, '422723197105190141');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008503', '000176', 'Áõ¹ðÏã', null, null, null, '15972726046', null, '00000', 0, '1', '0', '0', null, null, null, '15972726046', null, null, '7qShW2vwFXfbJJUq/xXo7Xq//aBv7c3l', null, '1103', null, null, null, '422723197208021922');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000003628', '000020', 'Îâ´ºÁá', null, null, null, '15717209706', null, '00000', 0, '1', '0', '0', null, null, null, '15717209706', null, null, '5kUX<2AaEpzwfcjN6HO22iyv5/tWWVPq', null, '1103', null, null, null, '420523197004294344');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000003628', '000021', 'ÎºÃ÷Õä', null, null, null, '13972990092', null, '00010', 0, '1', '0', '0', null, null, null, '13972990092', null, null, 'td2vugWanqzwfcjN6HO22iyv5/tWWVPq', null, '1103', null, null, null, '420626197605010014');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000003628', '000022', 'Îâ´ºÁá', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, '5kUX<2AaEpzwfcjN6HO22iyv5/tWWVPq', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001425', '000036', 'Àî´«Îä', null, null, '·¨ÈË', null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, '5/GHsPlLlmq7LS6ROn3doOidi2Ab<5Sw', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001425', '000037', 'ÅíÔ¶¾Õ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, '5/GHsPlLlmq7LS6ROn3doOidi2Ab<5Sw', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007217', '000042', 'Â¦¹ðÁ¬', null, null, null, '15072563222', null, '00000', 0, '1', '0', '0', null, null, null, '15072563222', null, null, 'HVxUklngdH/nSJBzlwOyQ7zf6M0AskbF', null, '1103', null, null, null, '422723197309271525');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007217', '000043', '²Ìæ«Áá', null, null, null, '15871580688', null, '00000', 0, '1', '0', '0', null, null, null, '15871580688', null, null, 'HVxUklngdH/nSJBzlwOyQ7zf6M0AskbF', null, '1103', null, null, null, '420583198004060020');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000191', '000050', 'Ñ¦·¼·¼', null, null, null, '15882592459', null, '00000', 0, '1', '0', '0', null, null, null, '15882592459', null, null, 'PIcMRE<OKpEHTAiZe3f<wYblg8d<wIvs', null, '1103', null, null, null, '422723197408283740');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000191', '000051', 'Íò¿¡·æ', null, null, null, '13886656977', null, '00000', 0, '1', '0', '0', null, null, null, '13886656977', null, null, 'PIcMRE<OKpEHTAiZe3f<wYblg8d<wIvs', null, '1103', null, null, null, '420523198009200057');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000354', '000061', 'ÁõÄÈ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'fJNJ2qT9xYJO3UGm5pxVG9QhwFm7SjMo', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000354', '000062', '¶¡Ð¡ÁÖ', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'sUEwkVU<ELlO3UGm5pxVG9QhwFm7SjMo', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001435', '000070', 'ÀîÇå»ª', null, null, null, '15997525876', null, '00000', 0, '1', '0', '0', null, null, null, '15997525876', null, null, 'qtO3h3lmhujBbaLHKQW8oMJPj8nk1qqJ', null, '1103', null, null, null, '422723197603081028');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001435', '000071', '²ÜÇÇ', null, null, null, '18040648299', null, '00000', 0, '1', '0', '0', null, null, null, '18040648299', null, null, 'qtO3h3lmhujBbaLHKQW8oMJPj8nk1qqJ', null, '1103', null, null, null, '420583198609090046');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001435', '000072', '01', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'qtO3h3lmhujBbaLHKQW8oMJPj8nk1qqJ', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006852', '000078', '³ÂÁÕ', null, null, null, '13872598333', null, '00010', 0, '1', '0', '0', null, null, null, '13872598333', null, null, 'COQvbqImNypHwHlRf3RbU/QpoAz1hbfo', null, '1103', null, null, null, '420523197702040026');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006852', '000079', 'ÖÜ´úÃ÷', null, null, null, '18672901488', null, '00010', 0, '1', '0', '0', null, null, null, '18672901488', null, null, 'G1CXWnPwzCxHwHlRf3RbU/QpoAz1hbfo', null, '1103', null, null, null, '420523195812260098');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002124', '000091', 'Ñ¦ÈØ', null, null, null, '15572752218', null, '00000', 0, '1', '0', '0', null, null, null, '15572752218', null, null, 'uP6mOOf<TcNJLvxWHGH29ID<U2tB9nxL', null, '1103', null, null, null, '422723197407040026');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002124', '000092', 'ÀîÐ÷Ë«', null, null, null, '13807204139', null, '00010', 0, '1', '0', '0', null, null, null, '13807204139', null, null, 'uP6mOOf<TcNJLvxWHGH29ID<U2tB9nxL', null, '1103', null, null, null, '422723196601211031');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005729', '000125', 'Ò××ÏÇß', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'vvYSndYH4/gf1e9Z8LZqaXUNDb7sJtJd', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005729', '000126', 'Öì²¨', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'vvYSndYH4/gf1e9Z8LZqaXUNDb7sJtJd', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004398', '000129', '½­Ñà', null, null, '³öÄÉ', '15872628420', null, '00000', 0, '1', '0', '0', null, null, 'M', '15872628420', null, null, 'okcbT1odyor95Lkn8jxRWY5f5M8GRJi8', null, '1103', null, null, null, '421003198005061561');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004398', '000130', 'ÁõÀò', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'okcbT1odyor95Lkn8jxRWY5f5M8GRJi8', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004398', '000131', '½­Ñà', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'okcbT1odyor95Lkn8jxRWY5f5M8GRJi8', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001656', '000138', 'Èî½­½¿', null, null, null, '15997600398', null, '00000', 0, '1', '0', '0', null, null, null, '15997600398', null, null, 'KdZSc6/PvL4yAry0tSdu8LIc5jcybaix', null, '1103', null, null, null, '420583198406271920');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001656', '000139', '·½Æ½', null, null, null, '13997725318', null, '00000', 0, '1', '0', '0', null, null, null, '13997725318', null, null, 'KdZSc6/PvL4yAry0tSdu8LIc5jcybaix', null, '1103', null, null, null, '420523197504190058');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000398', '000148', 'Ò×°×Óñ', null, null, null, '13986751628', null, '00000', 0, '1', '0', '0', null, null, null, '13986751628', null, null, 'F4yLH4aIvSCZP/CJEFbgoGLpLzFZPezR', null, '1103', null, null, null, '422721197508110027');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000398', '000149', 'ÁºÂ××£', null, null, null, '13707209158', null, '00000', 0, '1', '0', '0', null, null, null, '13707209158', null, null, '6OrEamPPtpCCAVzjWaahMmLpLzFZPezR', null, '1103', null, null, null, '422723195002284314');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006451', '000165', 'Ö£ÀûÈØ', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'dD8XjQ6h8WWASFJ9dTnCdP0Yo4uOZOdh', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002711', '000024', '¶­Ö²Æ½', null, null, null, '13907203356', null, '00000', 0, '1', '0', '0', null, null, null, '13907203356', null, null, 'QJDIpy/32nrkLyNXXB7C5TXCAUtphPEN', null, '1103', null, null, null, '42050219620921003X');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002711', '000025', '¶­´Ï', null, null, null, '15571701236', null, '00000', 0, '1', '0', '0', null, null, null, '15571701236', null, null, 'QJDIpy/32nrkLyNXXB7C5TXCAUtphPEN', null, '1103', null, null, null, '420502198806220315');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004977', '000038', '¶ÅÄÝÄÈ', null, null, null, '18671774277', null, '00000', 0, '1', '0', '0', null, null, null, '18671774277', null, null, 'pBj3Qep1lJuRof4jWrFwonrapB9H1XTz', null, '1103', null, null, null, '420583198305010748');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004977', '000039', '¶ÅÀÚ', null, null, null, '18677214688', null, '00000', 0, '1', '0', '0', null, null, null, '18677214688', null, null, 'pBj3Qep1lJuRof4jWrFwonrapB9H1XTz', null, '1103', null, null, null, '420583198019160776');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007626', '000109', 'Ö£Ü¿Æ¼', null, null, null, '17771728997', null, '00000', 0, '1', '0', '0', null, null, null, '17771728997', null, null, 'htYcBbiDjRN42TGiOLZUHs408a8utDS8', null, '1103', null, null, null, '420583199004031929');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007626', '000110', '³ÂÓÂ', null, null, null, '13872623926', null, '00000', 0, '1', '0', '0', null, null, null, '13872623926', null, null, 'htYcBbiDjRN42TGiOLZUHs408a8utDS8', null, '1103', null, null, null, '420583197804082215');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007626', '000111', 'Ö£Ü¿Æ¼', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'htYcBbiDjRN42TGiOLZUHs408a8utDS8', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007626', '000112', '³ÂÓÂ', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'htYcBbiDjRN42TGiOLZUHs408a8utDS8', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005975', '000115', 'ÖÜÊ÷ÁÖ', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'mRrFbZsJ2m4kiW1AAm1Pt9tpZQ3650jd', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005975', '000116', 'ÇüÐÂÆ½', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'XmnAT<wk8bUkiW1AAm1Pt9tpZQ3650jd', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005813', '000120', 'ÐíÖÒ¹ó', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'cmCUjv2<OrgdFfWpnvylaopw73S49Ji9', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000398', '000150', 'Ò×°×Óñ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'F4yLH4aIvSCZP/CJEFbgoGLpLzFZPezR', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008294', '000151', 'Ò×°×Óñ', null, null, null, '13986751628', null, '00000', 0, '1', '0', '0', null, null, null, '13986751628', null, null, 'ngD1PGpLzqk9nyFrW0jDiLg3HmR<Fzwq', null, '1103', null, null, null, '422721197508110027');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008294', '000152', 'ÁºÂ××£', null, null, null, '13707209158', null, '00000', 0, '1', '0', '0', null, null, null, '13707209158', null, null, 'ubxePid5AxE9nyFrW0jDiLg3HmR<Fzwq', null, '1103', null, null, null, '422723195002284314');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000398', '000155', 'Á»Â××£', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'F', null, null, null, 'F4yLH4aIvSCZP/CJEFbgoGLpLzFZPezR', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008294', '000158', 'Ò×°×Óñ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'ngD1PGpLzqk9nyFrW0jDiLg3HmR<Fzwq', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008294', '000159', 'ÁºÂ××£', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'ubxePid5AxE9nyFrW0jDiLg3HmR<Fzwq', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001410', '000160', 'Ôøº£ÑÞ', null, null, null, '13872660060', null, '00010', 0, '1', '0', '0', null, null, null, '13872660060', null, null, 'f94EsXbjEWHBbaLHKQW8oCAvxcZFZv<5', null, '1103', null, null, null, '422723197304293725');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001410', '000161', 'ÕÅ½ø', null, null, null, '13972041454', null, '00010', 0, '1', '0', '0', null, null, null, '13972041454', null, null, 'UkOFabz2hEfBbaLHKQW8oCAvxcZFZv<5', null, '1103', null, null, null, '422723197208113712');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006712', '000014', 'ÀîÇÉÁá', null, null, '³öÄÉ', '13872528639', null, '10000', 0, '1', '0', '0', null, null, 'M', '13872528639', null, null, '5hWk<lwQnwxxvS/x8SIx3J6V2HnK5ZnC', null, '1103', null, null, null, '420583198908211522');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006712', '000015', 'ÁõÁè', null, null, '»á¼Æ', '15971621906', null, '00110', 1, '1', '0', '0', null, null, 'M', '15971621906', null, null, 'QdWbp6TKjRPjpjEeOSB7uZ6V2HnK5ZnC', null, '1103', null, null, null, '42050019760903652X');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006828', '000029', 'Òü¾ê', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, '6HRl04DwU3W6jVDS2Z4JfHtpwPCF8EF/', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006093', '000030', 'Áõ¹ðæÃ', null, null, null, '13507241876', null, '00000', 0, '1', '0', '0', null, null, null, '13507241876', null, null, 'cmDRjeex4djoR2lrjJzHaFjpjNVzV2JD', null, '1103', null, null, null, '420583198909183527');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006093', '000031', '¸¶ºêÇ¿', null, null, null, '13316842199', null, '00000', 0, '1', '0', '0', null, null, null, '13316842199', null, null, 'cmDRjeex4djoR2lrjJzHaFjpjNVzV2JD', null, '1103', null, null, null, '4205823197310250032');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001425', '000034', 'Àî´«Îä', null, null, null, '15972701519', null, '00000', 0, '1', '0', '0', null, null, null, '15972701519', null, null, '5/GHsPlLlmq7LS6ROn3doOidi2Ab<5Sw', null, '1103', null, null, null, '42272319670607001X');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001425', '000035', 'ÅíÔ¶¾Õ', null, null, null, '13197339463', null, '00000', 0, '1', '0', '0', null, null, null, '13197339463', null, null, '5/GHsPlLlmq7LS6ROn3doOidi2Ab<5Sw', null, '1103', null, null, null, '422723197107250021');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000456', '000044', '³Â¹â¾Õ', null, null, null, '18672100789', null, '00000', 0, '1', '0', '0', null, null, null, '18672100789', null, null, 'gclRL81MdIA/cg0Sl<CWB7Ic5jcybaix', null, '1103', null, null, null, '420583197608074023');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000456', '000045', 'Ò¦»ª', null, null, null, '13387265555', null, '00000', 0, '1', '0', '0', null, null, null, '13387265555', null, null, 'gclRL81MdIA/cg0Sl<CWB7Ic5jcybaix', null, '1103', null, null, null, '422723196904223435');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006055', '000048', '¹Åè¤', null, null, '»á¼Æ', null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'AYsH3c/HKbroR2lrjJzHaINZ4MMdm3As', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000874', '000055', 'ÐÜÎ¬´ä', null, null, null, '13217179696', null, '00000', 0, '1', '0', '0', null, null, null, '13217179696', null, null, 'e5ZeL<r6ieRmA1zN0dbshRMHBNA1232o', null, '1103', null, null, null, '420583198205183721');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000874', '000056', '¹¨ÎÀ¶«', null, null, null, '13477178888', null, '00000', 0, '1', '0', '0', null, null, null, '13477178888', null, null, 'e5ZeL<r6ieRmA1zN0dbshRMHBNA1232o', null, '1103', null, null, null, '422723196707191032');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000874', '000057', 'ÐÜÎ¬´ä', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'lADrqyhFHkd7eTwny<ILVz6NbZA98UEQ', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000874', '000058', '¹¨ÎÀ¶«', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'lADrqyhFHkd7eTwny<ILVz6NbZA98UEQ', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000456', '000063', '¿ï³¤Çå', null, null, '»á¼Æ ', null, null, '10000', 0, '1', '0', '0', null, null, 'F', null, null, null, 'ltqDjmsmw1ol2jQGlO69/3Zy116YH9cT', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000456', '000064', 'ÑîÐ¡Æ½', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'ltqDjmsmw1ol2jQGlO69/3Zy116YH9cT', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006828', '000084', '¶­¶ðÁÖ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'u6x6WglC9o1HwHlRf3RbUzoIfCDXwZC1', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000003011', '000085', '²ÌµÀÃ÷', null, null, null, '13507240985', null, '00000', 0, '1', '0', '0', null, null, null, '13507240985', null, null, 'gOPAdiqVTlvHT0ofx5km8BMHBNA1232o', null, '1103', null, null, null, '422421196611207619');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000003011', '000086', 'Áõ½ð·¼', null, null, null, '13085169856', null, '00000', 0, '1', '0', '0', null, null, null, '13085169856', null, null, 'VkAGVh<8xrvy5j8Db0xZLDXCAUtphPEN', null, '1103', null, null, null, '422421197211060843');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000003011', '000087', '²ÌµÀÃ÷', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'VkAGVh<8xrvy5j8Db0xZLDXCAUtphPEN', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000003011', '000088', 'Áõ½ð·¼', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'VkAGVh<8xrvy5j8Db0xZLDXCAUtphPEN', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004765', '000089', 'Öì¹úÇå', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'Rl/lrXSwf5/N9NCj5nfT5HFBz6jjWZ2Z', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004765', '000090', 'Ð¤ÓñÆ¼', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'Rl/lrXSwf5/N9NCj5nfT5HFBz6jjWZ2Z', null, '1103', null, null, null, null);
commit;
prompt 100 records committed...
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002124', '000093', 'Ñ¦ÈØ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'uP6mOOf<TcNJLvxWHGH29ID<U2tB9nxL', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007217', '000094', '²Ìæ«Áá', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'HVxUklngdH/nSJBzlwOyQ7zf6M0AskbF', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007217', '000095', '²Ìæ«Áá', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'HVxUklngdH/nSJBzlwOyQ7zf6M0AskbF', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006360', '000101', 'Ô¬·½ÖÞ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'cmDRjeex4djn1X0wapfg37orVINHzL2r', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006360', '000102', 'Ô¬·½ÖÞ', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'cmDRjeex4djn1X0wapfg37orVINHzL2r', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005975', '000103', 'ÇüÐÂÆ½', null, null, null, '13094174899', null, '00000', 0, '1', '0', '0', null, null, null, '13094174899', null, null, 'Bf8lGiGnOY6aChTnMdjsAttKmysEE5SV', null, '1103', null, null, null, '42272319710705002X');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005975', '000104', 'ºúÔ¶Çå', null, null, null, '13872517379', null, '00000', 0, '1', '0', '0', null, null, null, '13872517379', null, null, 'Bf8lGiGnOY6aChTnMdjsAttKmysEE5SV', null, '1103', null, null, null, '420523197209152235');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007745', '000121', 'Ðì´ºÑÞ', null, null, null, '13098411620', null, '00000', 0, '1', '0', '0', null, null, null, '13098411620', null, null, 'hrbyVEhLe0F3Dl3oX9xo9BMHBNA1232o', null, '1103', null, null, null, '42272319640620010X');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007745', '000122', 'Ò×¹ú', null, null, null, '13886662888', null, '00000', 0, '1', '0', '0', null, null, null, '13886662888', null, null, 'hrbyVEhLe0F3Dl3oX9xo9BMHBNA1232o', null, '1103', null, null, null, '420523196202110011');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002463', '000127', '³ÂÁá', null, null, null, '18771801505', null, '00010', 0, '1', '0', '0', null, null, null, '18771801505', null, null, 'O8n0PtuqZUwnHlzicCtYpwITJxukeVTG', null, '1103', null, null, null, '421003197910032926');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002463', '000128', 'Àî±¾Õä', null, null, null, '13477830000', null, '00010', 0, '1', '0', '0', null, null, null, '13477830000', null, null, 'evdxiU9MRMwnHlzicCtYpwITJxukeVTG', null, '1103', null, null, null, '420583197407270060');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001656', '000140', 'Èî½­½¿', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'n9tHdtfrUgZc7ArrChHYDZPsuV0WdRxZ', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001656', '000141', 'ÐÜÏþÀ¼', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'n9tHdtfrUgZc7ArrChHYDZPsuV0WdRxZ', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002249', '000144', 'ÕÔÀö»ª', null, null, null, '13972526636', null, '00000', 0, '1', '0', '0', null, null, null, '13972526636', null, null, '/nQW<x<E7vR6IsaAjiFssFcL0nNnCnDU', null, '1103', null, null, null, '422723196510054325');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002249', '000145', 'ÕÔÉú·ï', null, null, null, '13349769886', null, '00000', 0, '1', '0', '0', null, null, null, '13349769886', null, null, '/nQW<x<E7vR6IsaAjiFssFcL0nNnCnDU', null, '1103', null, null, null, '422723195808110049');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006055', '000049', '²Ì´ó¾ü', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'AYsH3c/HKbroR2lrjJzHaINZ4MMdm3As', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004398', '000068', '³ÂÖ¾æÚ', null, null, null, '18601357919', null, '00000', 0, '1', '0', '0', null, null, null, '18601357919', null, null, 'g7OOQ1TKMmv95Lkn8jxRWY5f5M8GRJi8', null, '1103', null, null, null, '430322197007168954');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004398', '000069', '½­Ñà', null, null, null, '15872628420', null, '00000', 0, '1', '0', '0', null, null, null, '15872628420', null, null, 'g7OOQ1TKMmv95Lkn8jxRWY5f5M8GRJi8', null, '1103', null, null, null, '421003198005061561');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006451', '000076', 'Ö£ÀûÈØ', null, null, null, '13986761066', null, '00010', 0, '1', '0', '0', null, null, null, '13986761066', null, null, 'dD8XjQ6h8WWASFJ9dTnCdP0Yo4uOZOdh', null, '1103', null, null, null, '422723197209164626');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006451', '000077', 'ÕÅÃ÷', null, null, null, '13907204406', null, '00010', 0, '1', '0', '0', null, null, null, '13907204406', null, null, 'dD8XjQ6h8WWASFJ9dTnCdP0Yo4uOZOdh', null, '1103', null, null, null, '422723197112132230');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002711', '000096', '¶­Ö²Æ½', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'F', null, null, null, 'QJDIpy/32nrkLyNXXB7C5TXCAUtphPEN', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000002711', '000097', '¶­´Ï', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'QJDIpy/32nrkLyNXXB7C5TXCAUtphPEN', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000001435', '000098', '²ÜÇÇ', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'qtO3h3lmhujBbaLHKQW8oMJPj8nk1qqJ', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006360', '000099', 'Ô¬·½ÖÞ', null, null, null, '15071750054', null, '00000', 0, '1', '0', '0', null, null, null, '15071750054', null, null, 'cmDRjeex4djn1X0wapfg37orVINHzL2r', null, '1103', null, null, null, '420583199406291029');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006360', '000100', '¸¶Á¬ºì', null, null, null, '13207228388', null, '00000', 0, '1', '0', '0', null, null, null, '13207228388', null, null, 'cmDRjeex4djn1X0wapfg37orVINHzL2r', null, '1103', null, null, null, '420583197401221030');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007593', '000105', 'ÕÔ¼Ò·¼', null, null, null, '13545733996', null, '00010', 0, '1', '0', '0', null, null, null, '13545733996', null, null, 'rBH/lYJ3S/h2ks<zlkvNoljpjNVzV2JD', null, '1103', null, null, null, '422723196606180043');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000007593', '000106', 'ÑîÇå»ª', null, null, null, '15392996099', null, '00010', 0, '1', '0', '0', null, null, null, '15392996099', null, null, 'MDY5eAb11NB2ks<zlkvNoljpjNVzV2JD', null, '1103', null, null, null, '422723196506160010');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005729', '000107', 'Ò××ÏÇß', null, null, null, '18164175383', null, '00000', 0, '1', '0', '0', null, null, null, '18164175383', null, null, 'vvYSndYH4/gf1e9Z8LZqaXUNDb7sJtJd', null, '1103', null, null, null, '420521199606040946');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005729', '000108', 'Öì²¨', null, null, null, '18995889977', null, '00000', 0, '1', '0', '0', null, null, null, '18995889977', null, null, 'vvYSndYH4/gf1e9Z8LZqaXUNDb7sJtJd', null, '1103', null, null, null, '420500197609175212');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008196', '000134', 'Ñ¦ÈØ', null, null, null, '15572752218', null, '00000', 0, '1', '0', '0', null, null, null, '15572752218', null, null, 'uP6mOOf<TcPKjQkY9MBMA6LiRenWMMjK', null, '1103', null, null, null, '422723197407040026');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008196', '000135', 'ÀîÐ÷Ë«', null, null, null, '13807204139', null, '00000', 0, '1', '0', '0', null, null, null, '13807204139', null, null, 'uP6mOOf<TcPKjQkY9MBMA6LiRenWMMjK', null, '1103', null, null, null, '422723196601211031');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008196', '000136', 'Ñ¦ÈØ', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'uP6mOOf<TcPKjQkY9MBMA6LiRenWMMjK', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008196', '000137', 'ÀîÐ÷Ë«', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'uP6mOOf<TcPKjQkY9MBMA6LiRenWMMjK', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006451', '000166', 'ÕÅÃ÷', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'dD8XjQ6h8WWASFJ9dTnCdP0Yo4uOZOdh', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005975', '000169', 'ÇüÐÂÆ½', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'Bf8lGiGnOY6aChTnMdjsAttKmysEE5SV', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000005975', '000170', 'ºúÔ¶Çå', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'Bf8lGiGnOY6aChTnMdjsAttKmysEE5SV', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006378', '000171', 'ºú»¶»¶', null, null, null, '13377989994', null, '00000', 0, '1', '0', '0', null, null, null, '13377989994', null, null, 'ezcrLDWxjLIDMSwOjONShCyv5/tWWVPq', null, '1103', null, null, null, '420583198511130716');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006378', '000172', '»Æ´äÆ½', null, null, null, '13317579975', null, '00000', 0, '1', '0', '0', null, null, null, '13317579975', null, null, 'ezcrLDWxjLIDMSwOjONShCyv5/tWWVPq', null, '1103', null, null, null, '420583198707251106');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006378', '000173', 'ºú»¶»¶', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'F', null, null, null, 'ezcrLDWxjLIDMSwOjONShCyv5/tWWVPq', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006378', '000174', 'ºú»¶»¶', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'ezcrLDWxjLIDMSwOjONShCyv5/tWWVPq', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008503', '000177', '½ðÓñÆ¼', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'M', null, null, null, '7qShW2vwFXfbJJUq/xXo7Xq//aBv7c3l', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000008503', '000178', 'Áõ¹ðÏã', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'M', null, null, null, '7qShW2vwFXfbJJUq/xXo7Xq//aBv7c3l', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000413', '000001', 'ÐÜÐ¡ÑÞ', null, null, null, '15971640224', null, '00000', 0, '1', '0', '0', null, null, null, '15971640224', null, null, 'TDz6NJKLN8A/cg0Sl<CWB9LterC2IBF4', null, '1103', null, null, null, '420583198812292241');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000413', '000002', 'Ö£Ô²Ô²', null, null, null, '15872520615', null, '00000', 0, '1', '0', '0', null, null, null, '15872520615', null, null, 'TDz6NJKLN8A/cg0Sl<CWB9LterC2IBF4', null, '1103', null, null, null, '420624198706166511');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000413', '000003', 'ÐÜÐ¡ÑÞ', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'M', null, null, null, 'TDz6NJKLN8A/cg0Sl<CWB9LterC2IBF4', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000000413', '000004', 'Ö£Ô²Ô²', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'F', null, null, null, 'TDz6NJKLN8A/cg0Sl<CWB9LterC2IBF4', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004981', '000005', 'Ñ¦Ò»Åô', null, null, null, '18671705668', null, '00000', 0, '1', '0', '0', null, null, null, '18671705668', null, null, 'BVgntMIf/zS6VVikNlng5xMHBNA1232o', null, '1103', null, null, null, '330381198612302630');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004981', '000006', 'ÀîÁ¢Ê¤', null, null, null, '13197309229', null, '00000', 0, '1', '0', '0', null, null, null, '13197309229', null, null, 'BVgntMIf/zS6VVikNlng5xMHBNA1232o', null, '1103', null, null, null, '330325196807172717');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004981', '000010', 'ÀîÁ¢Ê¤', null, null, '·¨ÈË´ú±í', null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'BVgntMIf/zS6VVikNlng5xMHBNA1232o', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006712', '000011', 'ÁõÁè', null, null, null, '15971621906', null, '00000', 0, '1', '0', '0', null, null, null, '15971621906', null, null, 'AE4xT0siNAfjpjEeOSB7uZ6V2HnK5ZnC', null, '1103', null, null, null, '42050019760903652X');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006712', '000012', 'ÀîÇÉÁá', null, null, null, '13872528639', null, '00000', 0, '1', '0', '0', null, null, null, '13872528639', null, null, '5hWk<lwQnwxxvS/x8SIx3J6V2HnK5ZnC', null, '1103', null, null, null, '420583198908211522');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004981', '000013', 'Ñ¦Ò»Åô', null, null, null, null, null, '10000', 0, '1', '0', '0', null, null, 'F', null, null, null, 'BVgntMIf/zS6VVikNlng5xMHBNA1232o', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004765', '000016', 'Öì¹úÇå', null, null, null, '18907205813', null, '00000', 0, '1', '0', '0', null, null, null, '18907205813', null, null, 'Rl/lrXSwf5/N9NCj5nfT5HFBz6jjWZ2Z', null, '1103', null, null, null, '422727197807281027');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004765', '000017', 'Ð¤ÓñÆ¼', null, null, null, '13997742555', null, '00000', 0, '1', '0', '0', null, null, null, '13997742555', null, null, 'Rl/lrXSwf5/N9NCj5nfT5HFBz6jjWZ2Z', null, '1103', null, null, null, '42272319640304042X');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006828', '000026', '¶­¶ðÁÖ', null, null, null, '13720226268', null, '00000', 0, '1', '0', '0', null, null, null, '13720226268', null, null, 'u6x6WglC9o1HwHlRf3RbUzoIfCDXwZC1', null, '1103', null, null, null, '420583198202020089');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006828', '000027', 'Òü¾ê', null, null, null, '15071778459', null, '00000', 0, '1', '0', '0', null, null, null, '15071778459', null, null, '6HRl04DwU3W6jVDS2Z4JfHtpwPCF8EF/', null, '1103', null, null, null, '420582198111180048');
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006093', '000032', 'µËÔÆÔÆ', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'QAyC1vZ7UHDSuP8f6UyhukfbMFe2Lw12', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000006093', '000033', '¸¶Á¬ºì', null, null, null, null, null, '00110', 1, '1', '0', '0', null, null, 'F', null, null, null, 'D<mY5fGVIrYnwdpofUPEfUfbMFe2Lw12', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004977', '000040', '¶ÅÄÝÄÈ', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'M', null, null, null, 'pBj3Qep1lJuRof4jWrFwonrapB9H1XTz', null, '1103', null, null, null, null);
insert into CB_USER_INF (uif_cstno, uif_userno, uif_username, uif_alias, uif_department, uif_jobtitle, uif_mobile, uif_email, uif_right, uif_authlvl, uif_logontype, uif_stt, uif_firstlogon, uif_pwd_set_date, uif_pretentinfo, uif_sex, uif_phone, uif_flag, uif_channelnumid, uif_channalcharpwd, uif_channelnumpwd, uif_channelcharid, uif_channalcharpay, uif_channelnumpay, uif_ctftyp, uif_ctfno)
values ('0000004977', '000041', '¶ÅÀÚ', null, null, null, null, null, '00000', 0, '1', '0', '0', null, null, 'F', null, null, null, 'pBj3Qep1lJuRof4jWrFwonrapB9H1XTz', null, '1103', null, null, null, null);
commit;
prompt 160 records loaded
prompt Enabling triggers for CB_USER_INF...
alter table CB_USER_INF enable all triggers;
set feedback on
set define on
prompt Done.
