CREATE TABLE DP_CNAPS_BANK
(
  BANK_CODE      VARCHAR2(12 CHAR),
  STATUS         CHAR(1 CHAR),
  CATEGORY       VARCHAR2(2 CHAR),
  CLS_CODE       VARCHAR2(3 CHAR),
  DREC_CODE      VARCHAR2(12 CHAR),
  NODE_CODE      VARCHAR2(4 CHAR),
  SUPRLIST       VARCHAR2(70 CHAR),
  PBC_CODE       VARCHAR2(12 CHAR),
  CITY_CODE      VARCHAR2(4 CHAR),
  ACCT_STATUS    VARCHAR2(1 CHAR),
  ASALTDT        VARCHAR2(8 CHAR),
  ASALTTM        VARCHAR2(14 CHAR),
  LNAME          VARCHAR2(60 CHAR),
  SNAME          VARCHAR2(20 CHAR),
  ADDR           VARCHAR2(60 CHAR),
  POSTCODE       VARCHAR2(6 CHAR),
  TEL            VARCHAR2(30 CHAR),
  EMAIL          VARCHAR2(30 CHAR),
  EFFDATE        VARCHAR2(8 CHAR),
  INVDATE        VARCHAR2(8 CHAR),
  ALT_DATE_TIME  DATE,
  ALT_TYPE       CHAR(1 CHAR),
  ALT_ISSNO      VARCHAR2(8 CHAR),
  REMARK         VARCHAR2(60 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


