CREATE TABLE T_APP_TICKET
(
  APP_TICKET    CHAR(32 BYTE),
  APP_CODE      VARCHAR2(20 BYTE),
  CUST_ID       VARCHAR2(50 BYTE),
  CUST_ID_TYPE  VARCHAR2(20 BYTE),
  GEN_TIME      TIMESTAMP(6),
  LOGIN_TICKET  CHAR(32 BYTE),
  REF_GEN_TIME  TIMESTAMP(6),
  VERSION       INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


