CREATE TABLE T_CERT_20151204
(
  ID_CERT        NUMBER,
  ALIAS          VARCHAR2(60 CHAR),
  MEDIA          VARCHAR2(1 CHAR),
  CERT_TYPE      VARCHAR2(10 CHAR),
  DNISO          VARCHAR2(255 CHAR),
  ACCT_NO        VARCHAR2(32 CHAR),
  KEY_NO         VARCHAR2(20 CHAR),
  E_NAME         VARCHAR2(50 CHAR),
  C_NAME         VARCHAR2(50 CHAR),
  STATUS         VARCHAR2(1 CHAR),
  ID_TYPE        VARCHAR2(1 CHAR),
  ID_NO          VARCHAR2(30 CHAR),
  UPD_DATE       DATE,
  CRE_DATE       DATE,
  APPLY_MODE     VARCHAR2(20 CHAR),
  UB_CODE        VARCHAR2(5 CHAR),
  OVER_DATE      DATE,
  REF_CODE       VARCHAR2(32 CHAR),
  AUTH_CODE      VARCHAR2(32 CHAR),
  DOWNLOAD_CODE  VARCHAR2(60 CHAR),
  PAY_DATE       DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


