CREATE TABLE T_CERT_BIND_ACCT
(
  ID_CERT_BIND_ACCT  NUMBER,
  ID_CERT            INTEGER,
  BIND_CODE          VARCHAR2(32 CHAR),
  UB_CODE            VARCHAR2(5 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


