CREATE TABLE T_DICT_ADDRESS_20151125
(
  ID_ADDRESS   NUMBER,
  CODE         VARCHAR2(6 CHAR),
  PARENT_ID    INTEGER,
  NAME         VARCHAR2(50 CHAR),
  STATUS       VARCHAR2(1 CHAR),
  UPDATE_DATE  DATE,
  TYPE         VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


