CREATE TABLE T_DICT_BANK
(
  CODE         VARCHAR2(3 CHAR),
  NAME         VARCHAR2(50 CHAR),
  ATTRIB       VARCHAR2(30 CHAR),
  STATUS       VARCHAR2(1 CHAR),
  IDX_NUM      INTEGER,
  UPDATE_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


