CREATE TABLE T_JUMP_TICKET
(
  JUMP_TICKET   CHAR(32 BYTE),
  APP_CODE      VARCHAR2(20 BYTE),
  ATTACHMENT    VARCHAR2(255 BYTE),
  CUST_ID       VARCHAR2(50 BYTE),
  CUST_ID_TYPE  VARCHAR2(20 BYTE),
  DEADLINE      TIMESTAMP(6),
  GEN_TIME      TIMESTAMP(6),
  LOGIN_TICKET  CHAR(32 BYTE),
  REF_DEADLINE  TIMESTAMP(6),
  REF_GEN_TIME  TIMESTAMP(6),
  VERSION       INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


