CREATE TABLE T_LOGIN_TICKET
(
  LOGIN_TICKET      CHAR(32 BYTE),
  APP_CODE          VARCHAR2(20 BYTE),
  APP_CONTEXT_ROOT  VARCHAR2(20 BYTE),
  CUST_ID           VARCHAR2(50 BYTE),
  CUST_ID_TYPE      VARCHAR2(20 BYTE),
  GEN_TIME          TIMESTAMP(6),
  LOGOUT_TIME       TIMESTAMP(6),
  REF_GEN_TIME      TIMESTAMP(6),
  REF_LOGOUT_TIME   TIMESTAMP(6),
  REF_UPD_TIME      TIMESTAMP(6),
  UPD_TIME          TIMESTAMP(6),
  VALID_FLAG        CHAR(1 BYTE),
  VERSION           INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


