CREATE TABLE T_NATIVE_BANK_20150812
(
  SZJDDM       VARCHAR2(6 CHAR),
  ZFHHH        VARCHAR2(12 CHAR),
  ZT           VARCHAR2(1 CHAR),
  LB           VARCHAR2(2 CHAR),
  HBDM         VARCHAR2(3 CHAR),
  SSZJCYZHH    VARCHAR2(12 CHAR),
  SFHCSDM      INTEGER,
  QSZHZT       VARCHAR2(1 CHAR),
  ZFHHM        VARCHAR2(60 CHAR),
  ZFHJC        VARCHAR2(20 CHAR),
  DZ           VARCHAR2(60 CHAR),
  YB           VARCHAR2(6 CHAR),
  DHHM         VARCHAR2(30 CHAR),
  UPDATE_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


