CREATE TABLE T_ACCOUNT
(
  ID_ACCOUNT      INTEGER,
  ACCT_NO         VARCHAR2(32 CHAR),
  UB_CODE         VARCHAR2(5 CHAR),
  CID             VARCHAR2(15 CHAR),
  STATUS          VARCHAR2(1 CHAR),
  FIN_ACCT_NO     VARCHAR2(20 CHAR),
  ACCT_TYPE       VARCHAR2(1 CHAR)              DEFAULT '0',
  OWNER_NAME      VARCHAR2(50 CHAR),
  ACCT_ALIAS      VARCHAR2(20 CHAR),
  ID_TYPE         VARCHAR2(1 CHAR),
  ID_NO           VARCHAR2(30 CHAR),
  CCY             VARCHAR2(2 CHAR),
  SUB_BRANCH      VARCHAR2(50 CHAR),
  OPEN_DATE       DATE,
  OVER_DATE       DATE,
  BRANCH          VARCHAR2(20 CHAR),
  VOUCHER_NO      VARCHAR2(12 CHAR),
  VOUCHER_STATUS  VARCHAR2(1 CHAR),
  FINC_DATE       DATE,
  CRE_DATE        DATE,
  UPD_DATE        DATE,
  VERSION         INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN T_ACCOUNT.FINC_DATE IS '理财卡开通日期';


