CREATE TABLE T_ACCT_FUNC_ATTR
(
  ID_ACCT_FUNC       NUMBER,
  ID_ACCT_FUNC_ATTR  NUMBER,
  KEYNAME            VARCHAR2(50 CHAR),
  VALUE              VARCHAR2(50 CHAR),
  REG_DATE           DATE,
  UPD_DATE           DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


