CREATE TABLE T_ACCT_FLOW
(
  ID_ACCT_FLOW  NUMBER,
  ACCT_NO       VARCHAR2(32 CHAR),
  UB_CODE       VARCHAR2(5 CHAR),
  CID           VARCHAR2(15 CHAR),
  FLAG          VARCHAR2(1 CHAR),
  CRE_DATE      DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


