CREATE TABLE T_ACCT_FUNC
(
  ID_ACCT_FUNC  NUMBER,
  UB_CODE       VARCHAR2(5 CHAR),
  ACCT_NO       VARCHAR2(32 CHAR),
  BUS_CODE      VARCHAR2(50 CHAR),
  REG_SRC       VARCHAR2(1 CHAR),
  REG_DATE      DATE,
  UPD_DATE      DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


