CREATE TABLE T_BULLETIN
(
  ID_BULLETIN      NUMBER,
  TITLE            VARCHAR2(120 CHAR),
  CONTENT          LONG,
  CRE_DATE         DATE,
  OVER_DATE        DATE,
  FORCE_READ       VARCHAR2(1 CHAR),
  FORCE_READ_DATE  DATE,
  UB_CODE          VARCHAR2(5 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


