CREATE TABLE T_CONTRACT_ACCT
(
  ID_CONTRACT_ACCT  NUMBER,
  ACCT_NO           VARCHAR2(32 CHAR),
  ACCT_NAME         VARCHAR2(80 CHAR),
  BANK              VARCHAR2(80 CHAR),
  PAY_LEVEL         VARCHAR2(1 CHAR),
  PURPOSE           VARCHAR2(200 CHAR),
  TACCT_TYPE        VARCHAR2(30 CHAR),
  MOBILE            VARCHAR2(15 CHAR),
  EMAIL             VARCHAR2(50 CHAR),
  CRE_DATE          DATE,
  ID_TAG            NUMBER,
  UB_CODE           VARCHAR2(5 CHAR),
  TACCT_NO          VARCHAR2(32 CHAR),
  ACCT_ALIAS        VARCHAR2(24 CHAR),
  PROVINCE          VARCHAR2(6 CHAR),
  CITY              VARCHAR2(6 CHAR),
  NATIVE_BANK       VARCHAR2(12 CHAR),
  ROUTE             VARCHAR2(2 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE T_CONTRACT_ACCT IS '
';


