CREATE TABLE T_CUSNT_ACCT
(
  ID_CUSNT_ACCT  NUMBER,
  CID            VARCHAR2(15 CHAR),
  ACCT_NO        VARCHAR2(32 CHAR),
  ACCT_NAME      VARCHAR2(80 CHAR),
  BANK_CODE      VARCHAR2(5 CHAR),
  TACCT_ALIAS    VARCHAR2(24 CHAR),
  PAY_LEVEL      VARCHAR2(1 CHAR),
  PURPOSE        VARCHAR2(200 CHAR),
  TACCT_TYPE     VARCHAR2(30 CHAR),
  MOBILE         VARCHAR2(15 CHAR),
  EMAIL          VARCHAR2(50 CHAR),
  REG_WAY        VARCHAR2(1 CHAR),
  CRE_DATE       DATE,
  ID_TAG         NUMBER,
  PROVINCE       VARCHAR2(20 CHAR),
  CITY           VARCHAR2(20 CHAR),
  NATIVE_BANK    VARCHAR2(12 CHAR),
  ROUTE          VARCHAR2(2 CHAR),
  NXY_BANK_NO    VARCHAR2(100 CHAR),
  NXY_BANK_NAME  VARCHAR2(100 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE T_CUSNT_ACCT IS '登记渠道有以下几种：
0－往来帐户管理中登记，以及转帐时登记(包括预约转帐时选择要求登记) 可正常使用
1－预约转帐时选择不登记，（该笔预约失效后删除）
';


