CREATE TABLE T_CUSTOMER
(
  ID_CUSTOMER      NUMBER,
  UB_CODE          VARCHAR2(5 CHAR),
  CID              VARCHAR2(15 CHAR),
  NAME             VARCHAR2(50 CHAR),
  GENDER           VARCHAR2(1 CHAR),
  LOGIN_PWD        VARCHAR2(80 CHAR),
  MOBILE           VARCHAR2(15 CHAR),
  EMAIL            VARCHAR2(50 CHAR),
  VALID_INFO       VARCHAR2(100 CHAR),
  NICK_NAME        VARCHAR2(50 CHAR),
  CRE_DATE         DATE,
  UPD_DATE         DATE,
  STATUS           VARCHAR2(1 CHAR),
  ID_TYPE          VARCHAR2(1 CHAR),
  ID_NO            VARCHAR2(30 CHAR),
  LAST_LOGIN_DATE  DATE,
  LAST_FAIL_DATE   DATE,
  FAIL_COUNT       INTEGER,
  VERSION          INTEGER,
  PROFESSION       VARCHAR2(2 CHAR),
  ADDR             VARCHAR2(80 CHAR),
  POSTAL_CODE      VARCHAR2(6 CHAR),
  PHONE            VARCHAR2(20 CHAR),
  KERNEL_ID        VARCHAR2(12 CHAR),
  FIRST_LOGIN      CHAR(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN T_CUSTOMER.STATUS IS '包括是否需要修改密码';


