CREATE TABLE T_LOANS_FLOW
(
  ID_FLOW         NUMBER,
  T_DUE_ID        VARCHAR2(50 CHAR),
  T_DUE_SX_ID     VARCHAR2(12 CHAR),
  T_CURRENCY      VARCHAR2(2 CHAR),
  T_AMOUNT        NUMBER(15,2),
  T_BALANCE       NUMBER(15,2),
  T_EXTENDS_DATE  DATE,
  T_DUE_DATE      DATE,
  T_RATE          NUMBER(13,8),
  T_COST          NUMBER(15,2),
  T_STATES        VARCHAR2(50 CHAR),
  T_LOAN_NO       VARCHAR2(50 CHAR),
  T_LOAN_KEY      VARCHAR2(12 CHAR),
  T_REF_NO        VARCHAR2(60 CHAR),
  T_TRAN_NO       VARCHAR2(60 CHAR),
  T_AMI           NUMBER(15,2),
  STATUS          VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


