CREATE TABLE T_LOANS_REFUND_FLOW
(
  ID_FLOW            NUMBER,
  T_EVENT_DATE       VARCHAR2(50 CHAR),
  T_EVENT_TITLE      VARCHAR2(12 CHAR),
  T_TRAN_DES         VARCHAR2(30 CHAR),
  T_LOAN_NO          VARCHAR2(50 CHAR),
  T_LOAN_KEY         VARCHAR2(12 CHAR),
  T_TRAN_REC_NO      VARCHAR2(12 CHAR),
  T_REPAYMENT_TYPE   VARCHAR2(2 CHAR),
  T_CURRENCY         VARCHAR2(2 CHAR),
  T_RECOVERY_AMOUNT  NUMBER(15,2),
  T_REFERENCE        VARCHAR2(50 CHAR),
  T_PRE_PRI_AMT      NUMBER(15,2),
  T_PRE_FEE_AMT      NUMBER(15,2),
  T_PRE_INT_AMT      NUMBER(15,2),
  T_PRE_ODP_AMT      NUMBER(15,2),
  T_PRE_ODI_AMT      NUMBER(15,2),
  STATUS             VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


