CREATE TABLE T_MARKET_INFO
(
  CONTRACT_CODE   VARCHAR2(18 CHAR),
  CONTRACT_NAME   VARCHAR2(18 CHAR),
  AVG_PRICE       VARCHAR2(18 CHAR),
  BANLANCE_PRICE  VARCHAR2(18 CHAR),
  BIDPRICE1       VARCHAR2(18 CHAR),
  BIDPRICE2       VARCHAR2(18 CHAR),
  BIDPRICE3       VARCHAR2(18 CHAR),
  BIDPRICE4       VARCHAR2(18 CHAR),
  BIDPRICE5       VARCHAR2(18 CHAR),
  BIDWEIGHT1      VARCHAR2(18 CHAR),
  BIDWEIGHT2      VARCHAR2(18 CHAR),
  BIDWEIGHT3      VARCHAR2(18 CHAR),
  BIDWEIGHT4      VARCHAR2(18 CHAR),
  BIDWEIGHT5      VARCHAR2(18 CHAR),
  BOURSE_NO       VARCHAR2(18 CHAR),
  CLOSE_PRICE     VARCHAR2(18 CHAR),
  FALLING_LIMIT   VARCHAR2(18 CHAR),
  HIGH_PRICE      VARCHAR2(18 CHAR),
  HOLD_WEIGHT     VARCHAR2(18 CHAR),
  LOW_PRICE       VARCHAR2(18 CHAR),
  MARKET_SEQ      VARCHAR2(18 CHAR),
  MARKET_TIME     DATE,
  NEW_PRICE       VARCHAR2(18 CHAR),
  OFFPRICE1       VARCHAR2(18 CHAR),
  OFFPRICE2       VARCHAR2(18 CHAR),
  OFFPRICE3       VARCHAR2(18 CHAR),
  OFFPRICE4       VARCHAR2(18 CHAR),
  OFFPRICE5       VARCHAR2(18 CHAR),
  OFFWEIGHT       VARCHAR2(18 CHAR),
  OFFWEIGHT2      VARCHAR2(18 CHAR),
  OFFWEIGHT3      VARCHAR2(18 CHAR),
  OFFWEIGHT4      VARCHAR2(18 CHAR),
  OFFWEIGHT5      VARCHAR2(18 CHAR),
  OPEN_PRICE      VARCHAR2(18 CHAR),
  RASING_LIMIT    VARCHAR2(18 CHAR),
  RISE_FALL       VARCHAR2(18 CHAR),
  RISE_RANGE      VARCHAR2(18 CHAR),
  SEAT_NO         VARCHAR2(18 CHAR),
  TRADE_AMOUT     VARCHAR2(18 CHAR),
  TRADE_WEIGHT    VARCHAR2(18 CHAR),
  YESCLOSE_PRICE  VARCHAR2(18 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


