CREATE TABLE T_MENU_LINK
(
  ID_LINK  NUMBER,
  ID_MENU  NUMBER,
  FUNC_ID  VARCHAR2(20 CHAR),
  URL      VARCHAR2(100 CHAR),
  TARGET   VARCHAR2(20 CHAR),
  NAME     VARCHAR2(50 CHAR),
  SEQ      INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN T_MENU_LINK.URL IS '可以重写菜单链接，若没有，表示系统内链接，若有表示外部链接';


