CREATE TABLE T_MENU
(
  ID_MENU      NUMBER,
  FUNC_ID      VARCHAR2(20 CHAR),
  PARENT_ID    VARCHAR2(20 CHAR),
  TYPE         VARCHAR2(1 CHAR)                 DEFAULT '1',
  MENU_NAME    VARCHAR2(50 CHAR),
  DESCRIPTION  VARCHAR2(50 CHAR),
  URL          VARCHAR2(100 CHAR),
  IS_END       VARCHAR2(1 CHAR)                 DEFAULT '0',
  TARGET       VARCHAR2(20 CHAR),
  SEQ          INTEGER,
  STATUS       VARCHAR2(1 CHAR),
  IS_USUALLY   VARCHAR2(1 CHAR)                 DEFAULT '0',
  IS_SHORTCUT  VARCHAR2(1 CHAR)                 DEFAULT '0',
  IS_INCLUDE   VARCHAR2(1 CHAR)                 DEFAULT '0',
  CRE_DATE     DATE,
  UPD_DATE     DATE,
  VERSION      INTEGER
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


