CREATE TABLE T_SEQ_REG
(
  ID_SEQ_REG  NUMBER,
  SEQ_TYPE    VARCHAR2(128 CHAR),
  SECTION     VARCHAR2(128 CHAR),
  HI_CTR      NUMBER,
  LOW_CTR     INTEGER,
  SYNC_FLAG   VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


