CREATE TABLE T_TRANS_FLOW
(
  ID_FLOW          NUMBER,
  TACCT            VARCHAR2(32 CHAR),
  ROUTE            VARCHAR2(2 CHAR),
  TUNCODE          VARCHAR2(12 CHAR),
  TBANKNAME        VARCHAR2(50 CHAR),
  TACCTNAME        VARCHAR2(50 CHAR),
  PURPOSE          VARCHAR2(200 CHAR),
  TLEVEL           VARCHAR2(1 CHAR),
  ADDR             VARCHAR2(60 CHAR),
  DIRECTION        VARCHAR2(1 CHAR),
  SERVICE_CHARGE   NUMBER,
  PAY_ACCT_NAME    VARCHAR2(50 CHAR),
  PAY_BRANCH_NAME  VARCHAR2(60 CHAR),
  STATUS           VARCHAR2(1 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


